# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: 2026 Matteo Beretta
# SPDX-License-Identifier: CERN-OHL-P-2.0

"""Local overrides of the base parameters.

Generated by the editor. It is saved next to parameters.py, which loads it on
its own: what is written here wins over the base. To go back to the starting
design it is enough to delete this file.

Each entry is name: (expression, value). There are also the derived
parameters that changed value without changing expression, because
parameters.py holds the values already computed and cannot redo the sums on
its own.
"""

OVERRIDES = {
    # --- CLUTCH: the sliding clearance on the shaft ---
    # MEASURED on a clutch printed in ASA: hole drawn 5.40, read
    # with the calipers 5.20, so the machine's compensation is EXACTLY 0.20 -
    # that is the one the base declared, now confirmed by a subtraction
    # instead of assumed. With it the hole measures 5.15 on a 5 mm shaft, and
    # on that clearance the hub rattles: it goes down to 0.10,
    # which draws 5.30, measures 5.10 and still slides on by hand.
    #
    # Note for whoever reads this in six months: raising Comp_hole_printing
    # to 0.25 was wrong and must NOT be repeated. It came from a symptom -
    # "the shaft is tight" - read on a part printed with the PREVIOUS
    # geometry, where the hole was a net 5.0: the compensation is not deduced
    # from a symptom, it is obtained by subtracting the measured from the
    # drawn.
    "Cl_clutch_shaft": ("0.10 mm", 0.10),
    "D_hole_clutch": ("D_shaft + Cl_clutch_shaft + Comp_hole_printing", 5.3),
    "D_mouth_hole_clutch": ("D_hole_clutch + 0.6 mm", 5.9),
    # The chord of the hole follows the clearance as the diameter does: with
    # 0.10 of clearance and 0.20 of compensation the flat of the hole stands
    # 0.15 above the shaft's flat, not 0.175 as in the base.
    "Z_flat_hole": ("Z_flat_shaft + (Cl_clutch_shaft + Comp_hole_printing) / 2", 2.15),
    # --- COLLAR: the two angles ---
    # The arc stops where what the collar really carries ends. From 72 to 110
    # degrees there was neither a screw, nor an ear, nor a paddle, and the
    # opening of the body to be covered ends at 29.5: it was 38 degrees of
    # free shelf, left over from the electronics bay that is no longer there.
    # They take with them their slice of the face of the front flange too,
    # which is the largest ceiling on supports of the part. 78 = 71.9 of the
    # head of the box, plus the material round the boss of the ear, plus
    # margin.
    "Ang_collar_pivot": ("78 deg", 78.0),
    # The play for chasing the screws of the base plate is not all needed, and
    # the pocket the flat bottom leaves for the bracket is its outline SWEPT
    # over this angle: every degree less is less overhanging surface.
    # +-3 degrees and not +-2: remounting the reference wheel showed +-2 short
    # of the real position of the base plate's screws. The extra degree costs
    # overhang on the swept pocket: see the commit for the number measured on
    # the solid.
    "Halfw_slot_collar": ("3 deg", 3.0),

    # --- WHEEL BODY (reference, not printed) ---
    "Chord_slot": ("2 * sqrt((D_body / 2) ^ 2 - (D_body / 2 - Dp_slot_front) ^ 2)", 71.2952),   # derived: only the value changes
    "Dp_slot_front": ("8.5 mm", 8.5),

    # --- COLLAR ---
    # A consequence of the slot at 8.5: its bottom went down from r 76 to
    # r 70.5, and the gasket at r 72 found itself under the slot instead of
    # inside the full face. The groove (70.5..73.5) coincided with the bottom
    # of the slot and with the labyrinth rib (71..73): the collar's profile
    # crossed itself and the gasket had nothing to press on. Moving it to 68.5
    # the groove sits at 67..70, a millimetre below the rib, and the face it
    # presses on is full again.
    "R_gasket": ("68.5 mm", 68.5),
    "R_in_flange_collar": ("R_gasket - 6 mm", 62.5),   # derived: only the value changes

    # --- CLUTCH: the collar that carries the grub's insert ---
    # 25 and not 30: at Ø30 the collar reaches 15.0 from the shaft axis and the heads of the
    # motor screws start at 15.63 (holes 26 apart on a square, that is 18.38
    # from the axis, minus the radius of the M3 head). Six tenths of clearance
    # on a part that turns and is fitted by hand are not clearance: they are
    # a collision found while screwing. At Ø25 the clearance becomes 3.1.
    #
    # The constraint on the other side - the collar must stay outside the
    # wheel body - loosens going down, it does not tighten: at Ø25 the point
    # nearest the disc axis goes from r 82.5 to r 85, that is six millimetres
    # outside the body instead of three and a half. And the M3 insert, 3 long,
    # still fits: from the shaft hole (r 2.65) to the edge of the collar
    # (r 12.5) there are 9.85 left.
    "D_collar_grub": ("25 mm", 25.0),

    # --- SENSOR ---

    # Air gap chosen by MEASUREMENT, not by datasheet. Seven trials with the
    # AS5600 powered at 3.3 V: the AGC stays at 128 - full scale - at any
    # height, so it discriminates nothing and the criterion is the magnitude.
    # Between air gaps 0.07 and 1.27 the magnitude goes from 893 to 759, that
    # is it drops 15% over the whole range: there is no optimum to aim at,
    # there is a plateau. All the points stand between 2.2 and 2.6 times the
    # threshold under which MD goes off (~350), so the field is not the
    # constraint and the air gap is chosen for mechanical reasons: underneath
    # there is a magnet turning flush with a still chip, and half a
    # millimetre of clearance is worth more than 5% of field. 1.2 is the
    # value tried with the 5.2 foot, full turn, excursion over the turn 4.1%:
    # the best of all the trials.
    "Gap_nominal": ("1.2 mm", 1.2),
    "H_rest_module": ("Th_spacer_magnet + Th_magnet + Th_glue_stack_magnet + Gap_nominal + H_body_chip", 5.13),   # derived: only the value changes

    # The wire passage on the sensor bracket 1 mm wider than the base,
    # so the four wires lie in with the JST crimped on. The two below are
    # derived from it and only change value (parameters.py does not redo sums).
    "W_passage_wires": ("4.5 mm", 4.5),
    "Off_boss_cable": ("(W_passage_wires + D_boss_cover_sensor) / 2 + 0.5 mm", 6.625),   # derived: only the value changes
    "Fil_mouth_passage_wires": ("2 * (Halfw_relief - W_passage_wires / 2)", 4.70),   # derived: only the value changes

    # A wider series of test feet: from 4.8-5.4 (air gaps
    # 0.87-1.47) to 4.6-5.8 (0.67-1.87), symmetric around the 5.2 foot that
    # gave the best run (1.27, see Gap_nominal above) and not below the 0.5 mm
    # the gap must keep: one foot more under, two over, for a magnet glued
    # higher or lower than the reference build's.
    "H_min_foot_test": ("4.6 mm", 4.6),
    "N_foot_test": ("7", 7),

    # (The reading window's angle is not overridden here: it is the METAL
    # body's window, which the collar's follows - Ang_window_body in the
    # base, estimated from a photo of the reference wheel.)

    # The wheel body went into the collar groove with effort: +0.3 mm on the set-back of the FRONT flange's inner face -
    # the face that prints on the supports (collar printed telescope side
    # down), rough and in excess, which is where fits want more clearance
    # (project rule). The rear flange locates the body and does not change.
    "Cl_groove_collar": ("0.8 mm", 0.8),
}
