# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: 2026 Matteo Beretta
# SPDX-License-Identifier: CERN-OHL-P-2.0
"""English texts of the parameters editor (ui.py), of the dimension chains
it shows and of the assembly plan drawn in it. Same keys as texts_editor_it.py:
texts_editor.py stops if they differ."""

TEXTS = {
    # --- the page of the parameters editor ---
    'ui.title': 'Wheelly — parameters',
    'ui.h1': 'parameters',
    'ui.reset': 'Reset',
    'ui.changes': 'Changes',
    'ui.make_step': 'Make the STEP files',
    'ui.export': 'Export parameters_local.py',
    'ui.search': 'Search by name or description…',
    'ui.f_mod': 'changed',
    'ui.f_mod_tip': 'Only the parameters you have changed',
    'ui.f_s': 'S only',
    'ui.f_s_tip': 'Only the design choices, the ones free to change',
    'ui.leg_m': 'M measured on the part',
    'ui.leg_s': 'S design choice',
    'ui.leg_d': 'D derived',
    'ui.leg_r': 'R from the catalogue',
    'ui.zoom_out': 'Zoom out',
    'ui.zoom_in': 'Zoom in',
    'ui.to_dim': 'dim',
    'ui.to_dim_tip': 'Frame the selected dimension',
    'ui.fit': 'fit',
    'ui.fit_tip': 'Put the whole drawing back in the frame',
    'ui.chains': 'Dimension chains',
    'ui.cad_title': 'STEP solids and full check',
    'ui.regenerate': 'Regenerate',
    'ui.publish': 'Move the files to out/',
    'ui.close': 'Close',
    'ui.copy': 'Copy',
    'ui.origin_S': 'design choice — free to change',
    'ui.origin_M': 'measured on the part — changes only by measuring again',
    'ui.origin_D': 'derived — change the parameter it comes from',
    'ui.origin_R': 'from the catalogue — comes from the component datasheet',
    'ui.n_changed_1': '1 parameter changed',
    'ui.n_changed': '{n} parameters changed',
    'ui.gen_failed': 'generation failed',
    'ui.n_fail_1': '1 check does not pass',
    'ui.n_fail': '{n} checks do not pass',
    'ui.all_pass': 'all checks pass',
    'ui.no_match': 'No parameter matches.',
    'ui.not_drawn': 'This dimension appears in no generated drawing: it is in <b>{where}</b>.',
    'ui.no_drawing': 'Drawing not available.',
    'ui.no_checks': 'No check run.',
    'ui.not_traceable': '<b>{name}</b> cannot be traced in this drawing',
    'ui.kind_diametro': 'diameter',
    'ui.kind_raggio': 'radius',
    'ui.kind_interasse': 'centre distance',
    'ui.kind_lunghezza': 'length',
    'ui.kind_distanza': 'distance from the centre',
    'ui.kind_ascissa': 'offset in X',
    'ui.kind_ordinata': 'offset in Y',
    'ui.kind_spessore': 'thickness',
    'ui.kind_other': 'match',
    'ui.from_drawing_n': ' in {n} places (from the drawing)',
    'ui.from_drawing': ' (from the drawing)',
    'ui.unverified_1': ' &middot; <i>not verified: one place has this number, but the drawing does not say it is this one</i>',
    'ui.too_many': ' &middot; <i>this value comes back in {n} places of the drawing: too many for it to mean anything</i>',
    'ui.ambiguous': ' &middot; <i>{n} places have this number: which one is its own, the editor does not know</i>',
    'ui.lang': 'en',
    'ui.generating': 'Generating…',
    'ui.diff_title': 'Changes against the file on disk',
    'ui.export_title': 'differences from the base — save them in src/parameters_local.py',
    'ui.copied': 'Copied',
    'ui.expr_mismatch': 'The expression would give {calc}, the file says {file}.',
    'ui.saved': '{n} files saved in out/',
    'ui.old_removed': ' — {n} old ones removed',
    'ui.generated': '{n} files generated',
    'ui.pill_chains': '{n} dimension chains',
    'ui.pill_audit': '{n} audit checks',
    'ui.pill_fail': ' — {n} do not pass',
    'ui.pill_all_pass': ' — all pass',
    'ui.published': '{n} files in out/',
    'ui.published_removed': ', {n} removed',
    'ui.unsaved': 'Generated with {n} parameters not yet saved to <b>src/parameters.py</b>: ',
    'ui.unsaved_tail': '. Move the files to <b>out/</b> only if you export the parameters too, or the audit of build.py will find the divergence.',
    # --- the names of the drawings, on the tabs ---
    'tab.assembly_plan': 'assembly · plan',
    'tab.assembly_section': 'assembly · section',
    'tab.assembly_details': 'assembly · details 4:1',
    'tab.body_dimensioned': 'dimensioned body',
    'tab.flat_gasket': 'flat gasket',
    'tab.magnet_cap': 'magnet cap',
    'tab.arm_plan': 'arm plan',
    'tab.collar_plan': 'collar plan',
    'tab.sensor_bracket': 'sensor bracket',
    'tab.collar_section': 'collar section',
    'tab.clutch_section': 'clutch section',
    # --- the callouts of the assembly plan (drawings_assembly.plan) ---
    'plan.wheel_body': 'wheel body (reference)',
    'plan.filter_disc': 'filter disc (reference)',
    'plan.optical': 'optical envelope',
    'plan.magnet': 'AS5600 magnet (telescope side)',
    'plan.sensor_board': 'AS5600 board',
    'plan.bracket': 'sensor bracket (telescope side)',
    'plan.collar_screws': 'collar and bracket M3',
    'plan.collar': 'collar',
    'plan.head': 'box, flat head: USB and GX12',
    'plan.board': '30x70 board (estimate) on its panel',
    'plan.xiao': 'XIAO ESP32-S3',
    'plan.driver': 'TMC2209 with heatsink',
    'plan.mech': 'box - mechanical compartment',
    'plan.clutch': 'clutch',
    'plan.motor': 'NEMA14 motor',
    'plan.arm': 'motor arm',
    'plan.spring': 'preload spring',
    'plan.spring_cup': 'spring cup',
    'plan.pivot': 'pivot 5 + 2 F695ZZ bearings',
    'plan.leg_print': 'parts to print',
    'plan.leg_ref': 'reference: not printed',
    'plan.leg_bought': 'bought components',
    # --- the assembly section (drawings_assembly.section); the names it shares
    #     with the plan (wheel body, collar, clutch, arm, motor, legend) use
    #     the plan's keys ---
    'sec.face_camera': 'camera-side face',
    'sec.mid_plane_disc': 'disc mid-plane',
    'sec.face_telescope': 'telescope-side face',
    'sec.filter_disc': 'filter disc',
    'sec.magnet_board': 'magnet + AS5600 board',
    'sec.bracket_ring': 'sensor bracket (ring over the magnet)',
    'sec.gasket_groove': 'gasket groove r{r}',
    'sec.labyrinth_rib': 'labyrinth rib in the slot',
    'sec.spring_off_plane': 'spring (off plane)',
    'sec.pivot_off_plane': 'pivot (off plane)',
    'sec.box': 'box',
    # --- the scaled details (drawings_assembly.details) ---
    'det.title_a': 'A - the motor seated on the arm (4:1)',
    'det.shaft': 'shaft',
    'det.centring_seat': 'centring seat',
    'det.leadin_45': '45 degree lead-in, clears the fillet',
    'det.motor_hub': 'motor hub, with its measured fillet',
    'det.motor_flange_rests': 'the motor flange rests here',
    'det.title_b': 'B - the pivot joint (4:1)',
    'det.spotface': 'spotface, makes room for the flange',
    'det.setback_face': 'set-back face: does not touch the arm',
    'det.flange_only_rubs': 'flange: the only thing that rubs',
    'det.two_bearings': 'two F695ZZ, flanges outward',
    'det.collar_pivot': 'collar pivot',
    # --- the dimension chains (check_dimensions.py) ---
    'chk.wall_sum': 'walls + opening = H_body (error)',
    'chk.disc_in_opening_top': 'disc inside the opening, top',
    'chk.disc_in_opening_bottom': 'disc inside the opening, bottom',
    'chk.tread_in_knurled_band': 'tread inside the knurled band',
    'chk.hub_in_opening_top': 'hub inside the opening, top',
    'chk.hub_in_opening_bottom': 'hub inside the opening, bottom',
    'chk.shaft_grip_in_hub': 'shaft engagement in the hub',
    'chk.centre_distance': 'centre distance = R_disc + D_clutch/2 (error)',
    'chk.clutch_hub_vs_inner_wall': 'clutch hub vs inner wall',
    'chk.clutch_shoulders_vs_disc_rim': 'clutch shoulders vs disc rim',
    'chk.shoulder_below_tread': 'clutch hub: shoulder below the tread',
    'chk.shoulder_above_tread': 'clutch hub: shoulder above the tread',
    'chk.grub_collar_outside_body': 'grub collar outside the body',
    'chk.grub_collar_under_screw_heads': 'grub collar under the motor screw heads',
    'chk.grub_insert_height': 'grub insert height consistent (error)',
    'chk.motor_inner_corner_outside_body': 'motor inner corner outside the body',
    'chk.motor_holes_vs_arm_rim': 'motor M3 holes vs arm rim',
    'chk.motor_outer_corner_vs_box_wall': 'motor outer corner vs box wall',
    'chk.clutch_rim_vs_box_wall': 'clutch rim vs box wall',
    'chk.board_inside_box_wall': '30x70 board inside the box wall',
    'chk.half_chord_vs_clutch_radius': 'opening half-chord vs clutch radius',
    'chk.disc_rim_proud_of_flat': 'disc rim proud of the flat',
    'chk.clutch_clear_of_flat': 'clutch clear of the cut flat',
    'chk.window_half_width': 'window half-width consistent with the clearance (error)',
    'chk.r_pivot_consistent': 'R_pivot consistent with the perpendicular (error)',
    'chk.l_arm_consistent': 'L_arm consistent (error)',
    'chk.arm_axis_min_radius': 'arm axis minimum radius vs inner rim',
    'chk.pivot_hub_vs_body': 'pivot hub vs body surface',
    'chk.preload_consistent': 'design preload consistent (error N)',
    'chk.spring_force_margin_on_measured': 'spring force over the measured need (x)',
    'chk.motor_torque_margin': 'motor torque margin (holding/required)',
    'chk.spring_force_consistent': 'spring force consistent (error N)',
    'chk.box_wall_past_moving_parts': 'box wall past the moving parts',
    'chk.collar_reaches_box_end': 'collar reaches as far as the box',
    'chk.board_cut_past_column_c0': 'board cut past column C0',
    'chk.box_end_consistent': 'end of the box consistent with the head (error)',
    'chk.front_ear_b_consistent': 'front ear B consistent with the head (error)',
    'chk.collar_flange_vs_rotator': 'collar flange vs rotator envelope',
    'chk.collar_covers_box': 'collar covers the whole box',
    'chk.gasket_below_groove_bottom': 'gasket below the bottom of the slot',
    'chk.gasket_inside_m3_screws': 'gasket inside the M3 screws',
    'chk.gasket_outside_inner_flange': 'gasket outside the inner flange',
    'chk.labyrinth_rib_outside_groove': 'labyrinth rib outside the groove',
    'chk.spring_fitted_shorter': 'fitted spring shorter than free',
    'chk.compression_within_45': 'compression within 45% of the free length',
    'chk.bearing_seat_through': 'bearing seat through (flanges outside)',
    'chk.bracket_ring_clearance_magnet': 'bracket ring clearance on the magnet',
    'chk.bracket_ring_clear_of_pivot': 'bracket ring clear of the pivot',
    'chk.web_ring_to_m2_holes': 'web between bracket ring and M2 holes',
    'chk.foot_centres_module': 'the foot still centres the module on the magnet',
    'chk.magnet_clearance_printed_hole': 'magnet clearance in the printed bracket hole',
    'chk.air_gap_within_3': 'geometric air gap within 3 mm',
    'chk.air_gap_over_05': 'geometric air gap over 0.5 mm',
    'chk.bracket_inside_collar_rim': 'bracket inside the outer rim of the collar',
    'chk.paddle_on_bottom_screw': 'bracket paddle {n} on a screw of the base',
    'chk.bracket_in_rotator_only_boss': 'bracket in the rotator only with its boss',
    'chk.paddles_inside_collar_arc': 'paddles inside the arc of the collar',
    'chk.bracket_step_outside_board': 'bracket step outside the board',
    'chk.board_pad_past_components': 'board pad past the components',
    'chk.material_m2_hole_to_pad_edge': 'material between M2 hole and pad edge',
    'chk.material_beside_m2_hole': 'material beside the M2 hole in the pad',
    'chk.pad_reaches_past_screw': 'the pad reaches past the screw',
    'chk.recess_floor_material': 'recess floor, material left',
    'chk.recess_taller_than_components': 'recess taller than the tallest component',
    'chk.m2_screw_through_board': 'the M2 screw passes through the board',
    'chk.leadin_narrower_than_m2': 'lead-in narrower than the M2 screw',
    'chk.leadin_not_too_narrow': 'lead-in not too narrow',
    'chk.m2_not_below_boss': 'the M2 screw does not come out under the boss',
    'chk.m2_not_below_lowest_foot': 'the M2 screw does not come out under the lowest foot',
    'chk.m2_grip_in_boss': 'M2 screw engagement in the boss',
}
