# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: 2026 Matteo Beretta
# SPDX-License-Identifier: CERN-OHL-P-2.0
"""English texts of the wiring drawings and of the printed booklet.

One key, two catalogues: this file and texts_drawings_it.py must hold the same
keys (drawing_common.tr checks it). The drawings come out twice, with the
suffix _en and _it: the documentation points at _en, and _it is there for an
Italian reader with the booklet in hand.
"""

TEXTS = {
    # --- the board layout -------------------------------------------------
    "lay.svg_title": "Board layout and wires",
    "lay.svg_desc": ("30 x 70 perfboard cut on the head side: where each component sits on the "
                     "10 x 24 grid, and the same components with the wires and the star ground. "
                     "Generated from electronics.py and wiring.py."),
    "lay.title": "Board · component side, head on the left, wheel axis at the bottom (row 01)",
    "lay.s1": "1 · Where each component goes",
    "lay.leg.perfboard": "30 × 70 perfboard, 10 × 24 holes",
    "lay.leg.strip": "female sockets, with the rows of pins",
    "lay.leg.modulo": "XIAO and driver boards, on the sockets",
    "lay.leg.dis": "driver heatsink",
    "lay.leg.pow": "electrolytics (C1, C2)",
    "lay.leg.box": "terminal blocks and headers",
    "lay.leg.res": "resistors, lying flat",
    "lay.leg.dente": "panel guides",
    "lay.components": "Components",
    "lay.pins_in": "pins in {holes}",
    "comp.C1": "47 µF 63 V, driver VM",
    "comp.C2": "47 µF 63 V, 12 V input (optional)",
    "comp.J1": "phase A and B terminal block, four poles",
    "comp.J3": "12 V terminal block",
    "comp.J4": "sensor header, 4 poles",
    "comp.J5": "LED header, 2 poles",
    "comp.R1": "10 kΩ, EN pull-up",
    "comp.R2": "1 kΩ in series, UART",
    "comp.R3": "1 kΩ in series, LED",
    "lay.points": "Points",
    "pt.A": "single ground node: the negative of C1, in S02. One wire per branch from here.",
    "pt.B": "XIAO USB socket: flush with the outer face of the head.",
    "pt.C": "part removed by the cut: the board ends {mm} mm past column C0.",
    "pt.D": "fixing holes: only at the far end; those at the head go with the cut.",
    "pt.E": "panel guides: they square the board from the side, they do not cover it. It goes in from above.",
    "pt.F": "hole {hole}, to drill out to Ø2.7: the third screw, the one that holds the cut end.",
    "lay.s2": "2 · The wires, with the star ground",
    "lay.nets": "Nets",
    "net.vm": "12 V and VM",
    "net.stella": "star ground: the wires leaving the node",
    "net.gnd_pot": "power ground: lead of C1, − of C2",
    "net.gnd_log": "logic ground, local bus of its branch",
    "net.3v3": "XIAO 3V3",
    "net.segnale": "signals",
    "net.i2c": "sensor I²C",
    "net.faseA+": "phase A+ (black)",
    "net.faseA-": "phase A− (green)",
    "net.faseB+": "phase B+ (red)",
    "net.faseB-": "phase B− (blue)",
    "lay.cat5": "at J4: the colour of the sensor cable (CAT5) wire on each pin - {list}",
    "lay.star": "The star ground, as it is done here",
    "lay.star.1": "The node is the negative of C1, in S02: its lead goes short to the driver power GND (O03).",
    "lay.star.2": "THREE wires leave the node, and only three: to − of the 12 V block, to the driver logic GND (I02), to the XIAO GND (B08).",
    "lay.star.3": "Each branch then has its own local bus, which touches no other: from the XIAO the sensor and LED ground,",
    "lay.star.4": "from the driver logic GND, MS1 and MS2. No ground connects to another ground outside the node.",
    "lay.star.5": "C2, if fitted, sits on the pins of the block: its − goes to − of the block, not to the node.",
    "lay.wires": "Wires",
    "lay.wires_note": ("In brackets the hole: first as read FROM ABOVE, on the component side, "
                       "then as read FROM BELOW, on the solder side."),
    "lay.s3": "3 · The same board seen FROM BELOW, on the solder side",
    "lay.s3_note": ("The drawing is flipped the way the board is flipped; the letters still run left to right, "
                    "because they are printed on this face too."),
    "lay.warn.1": "WARNING: the orientation of the XIAO (D0–D6 on row R8) comes from the maker's pinout turned with the USB",
    "lay.warn.2": "to the left; the old layout had it the other way round. Check it on the real XIAO before soldering.",
    "lay.warn.3": "Positions and wires come from mechanics/wheelly-cad/src/electronics.py and wiring.py: moving a component there moves",
    "lay.warn.4": "the check that it clears the box as well. The bodies of terminal blocks, headers and resistors are catalogue ESTIMATES.",
    "lay.warn.5": "The wires are drawn smooth, with a white halo at crossings to show which is on top. They say what goes where, not the route.",
    # --- the connection drawings ------------------------------------------
    "sch.cable": "cable: {names}",
    "sch.tmc.title": "Connections XIAO · TMC2209",
    "sch.tmc.desc": ("The connections between the XIAO and the driver, with R1 as EN pull-up and R2 in "
                     "series on the UART TX. Holes on the grid printed on the board."),
    "sch.tmc.r1": "driver logic supply",
    "sch.tmc.r2": "one pulse, one microstep",
    "sch.tmc.r3": "direction of rotation",
    "sch.tmc.r4": "enable: low enables",
    "sch.tmc.r5": "pull-up between 3V3 and EN, leads in M09 and P09",
    "sch.tmc.r6": "TX to the UART, in series with leads in L10 and P10",
    "sch.tmc.r7": "RX from the same UART, direct",
    "sch.tmc.n1": "THE GROUND DOES NOT GO THROUGH HERE. The driver GND (I02) and the XIAO GND (B08)",
    "sch.tmc.n2": "both leave the node, the negative of C1 (S02), with one wire each.",
    "sch.tmc.n3": "Joining them would close the loop that pcb/README says not to close.",
    "sch.tmc.n4": "The driver's MS1 and MS2 go to its logic ground, inside its own branch.",
    "sch.as.title": "Connections XIAO · AS5600 and LED",
    "sch.as.desc": ("The connections between the XIAO, the sensor module and the status LED. "
                    "Holes on the grid printed on the board."),
    "sch.as.right": "AS5600 (J4) and LED (J5)",
    "sch.as.r1": "module supply, 3.3 V",
    "sch.as.r2": "sensor ground: logic bus branch",
    "sch.as.r3": "I²C data",
    "sch.as.r4": "I²C clock",
    "sch.as.r5": "LED drive, in series with leads in G10 and K10",
    "sch.as.r6": "LED return: same logic branch",
    "sch.as.n1": "These two grounds leave the XIAO GND and not the node: they are its branch",
    "sch.as.n2": "of the logic bus, and inside a branch the grounds may touch.",
    "sch.as.n3": "The module's 104 capacitor sits under its own board, not here.",
    "sch.as.n4": "SENSOR CABLE (CAT5), four wires, colours as soldered on the module: brown 3V3,",
    "sch.as.n5": "white-brown GND, blue SDA, green SCL. DIR is tied to GND on the module (jumper pad 2 - pad 1),",
    "sch.as.n6": "not through the cable. Cut back and insulated at this end: {free}.",
    "sch.pow.title": "Power · TMC2209, terminal blocks, motor and ground node",
    "sch.pow.desc": ("The four phases, the 12 V branch and the star ground. Not a block diagram but a LIST "
                     "OF WIRES: the two columns are the two ends, and a component is on one side or the "
                     "other depending on the wire. Holes on the grid printed on the board."),
    "sch.pow.left": "from this end",
    "sch.pow.right": "to this other",
    "sch.pow.r1": "phase A+, black wire",
    "sch.pow.r2": "phase A−, green wire",
    "sch.pow.r3": "phase B+, red wire",
    "sch.pow.r4": "phase B−, blue wire",
    "sch.pow.r5": "VM to + of C1: SHORT lead, the loop that matters",
    "sch.pow.r6": "from + of C1 to + of the 12 V block",
    "sch.pow.r7": "C2 in parallel on the input, optional",
    "sch.pow.r8": "driver power GND to − of C1: SHORT lead",
    "sch.pow.r9": "from the node to − of the block: first star wire",
    "sch.pow.r10": "from the node to the driver logic GND: second wire",
    "sch.pow.r11": "from the node to the XIAO GND: third wire",
    "sch.pow.n1": "THE GROUND NODE IS THE NEGATIVE OF C1, IN S02, and THREE WIRES AND ONLY THREE leave it.",
    "sch.pow.n2": "No branch connects to another branch: two grounds touching in two places close",
    "sch.pow.n3": "a loop, and part of the motor return runs along the USB shield to the camera.",
    "sch.pow.n4": "The two leads of C1 are cut short, straddling the VM and GND pins of the socket:",
    "sch.pow.n5": "the area of that loop counts more than any shielding downstream, and comes before",
    "sch.pow.n6": "the space it takes. That is why C1 stayed here and C2 moved.",
    "sch.pow.n7": "The phase colours are the motor's, not a choice: black and green one phase,",
    "sch.pow.n8": "red and blue the other. Swapping the two wires of ONE phase reverses the rotation.",
    # --- the sensor cable colours -----------------------------------------
    "col.brown": "brown",
    "col.white-brown": "white-brown",
    "col.blue": "blue",
    "col.green": "green",
    "col.white-green": "white-green",
    "col.white-blue": "white-blue",
    "col.orange": "orange",
    "col.white-orange": "white-orange",
    # --- the printed booklet ------------------------------------------------
    "pdf.title": "Wheelly · layout and connections",
    "pdf.p1": "Board · where each component goes",
    "pdf.p2": "Board · the wires seen from above and from below",
    "pdf.p3": "Board · the star ground and the list of wires",
    "pdf.p4": "Connections · driver, sensor and LED",
    "pdf.footer": "Wheelly · generated from the model on {date} · page {n} of {tot}",
    "pdf.p5": "Connections · power, phases and ground node",
}
