# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: 2026 Matteo Beretta
# SPDX-License-Identifier: CERN-OHL-P-2.0
"""Italian texts of the wiring drawings and of the printed booklet.

The same keys as texts_drawings_en.py (drawing_common.tr checks it). This is
the Italian localisation, not a leftover: the _it drawings are for an Italian
reader with the booklet in hand. Real accented letters, not apostrophes.
"""

TEXTS = {
    # --- the board layout ------------------------------------------------------
    "lay.svg_title": "Disposizione e fili della basetta",
    "lay.svg_desc": ("Basetta 30 x 70 tagliata dal lato della testa: dove sta ogni componente sulla "
                     "griglia 10 x 24, e gli stessi componenti con i fili e la massa a stella. "
                     "Generata da electronics.py e wiring.py."),
    "lay.title": "Basetta · vista dai componenti, testa a sinistra, asse della ruota in basso (riga 01)",
    "lay.s1": "1 · Dove sta ogni componente",
    "lay.leg.perfboard": "basetta 30 × 70, 10 × 24 fori",
    "lay.leg.strip": "zoccoli femmina, con le file di pin",
    "lay.leg.modulo": "scheda di XIAO e driver, sopra gli zoccoli",
    "lay.leg.dis": "dissipatore del driver",
    "lay.leg.pow": "elettrolitici (C1, C2)",
    "lay.leg.box": "morsetti e header",
    "lay.leg.res": "resistenze, coricate",
    "lay.leg.dente": "guide del pannellino",
    "lay.components": "Componenti",
    "lay.pins_in": "piedini in {holes}",
    "comp.C1": "47 µF 63 V, VM del driver",
    "comp.C2": "47 µF 63 V, ingresso 12 V (opzionale)",
    "comp.J1": "morsetto fasi A e B, quattro poli",
    "comp.J3": "morsetto 12 V",
    "comp.J4": "header sensore, 4 poli",
    "comp.J5": "header LED, 2 poli",
    "comp.R1": "10 kΩ, pull-up di EN",
    "comp.R2": "1 kΩ in serie, UART",
    "comp.R3": "1 kΩ in serie, LED",
    "lay.points": "Punti",
    "pt.A": "nodo di massa unico: il negativo di C1, in S02. Da qui un filo per ramo.",
    "pt.B": "presa USB dello XIAO: a filo della faccia esterna della testa.",
    "pt.C": "parte tolta col taglio: la basetta finisce {mm} mm oltre la colonna C0.",
    "pt.D": "fori di fissaggio: solo al capo lontano, quelli della testa se ne vanno col taglio.",
    "pt.E": "guide del pannellino: squadrano la basetta di lato, non la coprono. Si cala dall'alto.",
    "pt.F": "foro {hole}, da aprire col trapano a Ø2,7: è la terza vite, quella che tiene il capo tagliato.",
    "lay.s2": "2 · I fili, con la massa a stella",
    "lay.nets": "Reti",
    "net.vm": "12 V e VM",
    "net.stella": "massa a stella: i fili che partono dal nodo",
    "net.gnd_pot": "massa di potenza: reoforo di C1, − di C2",
    "net.gnd_log": "massa logica, bus locale del suo ramo",
    "net.3v3": "3V3 dello XIAO",
    "net.segnale": "segnali",
    "net.i2c": "I²C del sensore",
    "net.faseA+": "fase A+ (nero)",
    "net.faseA-": "fase A− (verde)",
    "net.faseB+": "fase B+ (rosso)",
    "net.faseB-": "fase B− (blu)",
    "lay.cat5": "su J4: il colore del filo del cavo del sensore (CAT5) su ogni pin - {list}",
    "lay.star": "La massa a stella, come si fa qui",
    "lay.star.1": "Il nodo è il negativo di C1, in S02: il suo reoforo va corto al GND di potenza del driver (O03).",
    "lay.star.2": "Dal nodo partono TRE fili, e solo tre: al − del morsetto 12 V, al GND logico del driver (I02), al GND dello XIAO (B08).",
    "lay.star.3": "Ogni ramo ha poi il suo bus locale, che non tocca gli altri: dallo XIAO la massa del sensore e del LED,",
    "lay.star.4": "dal GND logico del driver MS1 e MS2. Nessuna massa si collega a un'altra massa fuori dal nodo.",
    "lay.star.5": "C2, se c'è, sta sui pin del morsetto: il suo − va al − del morsetto, non al nodo.",
    "lay.wires": "Fili",
    "lay.wires_note": ("Fra parentesi il foro: prima come si legge DA SOPRA, dal lato dei componenti, "
                       "poi come si legge DA SOTTO, dal lato delle saldature."),
    "lay.s3": "3 · La stessa basetta vista DA SOTTO, dal lato delle saldature",
    "lay.s3_note": ("Il disegno è ribaltato come si ribalta la basetta; le lettere restano da sinistra a destra, "
                    "perché sono serigrafate anche su questa faccia."),
    "lay.warn.1": "ATTENZIONE: l'orientamento dello XIAO (D0–D6 sulla riga R8) viene dalla piedinatura del costruttore ruotata con l'USB",
    "lay.warn.2": "a sinistra; la disposizione vecchia lo aveva al contrario. Va verificato sullo XIAO vero prima di saldare.",
    "lay.warn.3": "Posizioni e fili vengono da mechanics/wheelly-cad/src/electronics.py e wiring.py: spostare un componente là sposta",
    "lay.warn.4": "anche il controllo che non tocchi la scatola. I corpi di morsetti, header e resistenze sono STIME di catalogo.",
    "lay.warn.5": "I fili sono disegnati morbidi, con l'alone bianco negli incroci: si legge quale passa sopra. Dicono cosa va dove, non per dove passano davvero.",
    # --- the connection drawings ---------------------------------------------
    "sch.cable": "cavo: {names}",
    "sch.tmc.title": "Collegamenti XIAO · TMC2209",
    "sch.tmc.desc": ("I collegamenti fra lo XIAO e il driver, con R1 come pull-up di EN e R2 in serie "
                     "sul TX della UART. Fori nella griglia stampata sulla basetta."),
    "sch.tmc.r1": "alimentazione logica del driver",
    "sch.tmc.r2": "un impulso, un microstep",
    "sch.tmc.r3": "verso di rotazione",
    "sch.tmc.r4": "abilitazione: bassa abilita",
    "sch.tmc.r5": "pull-up fra 3V3 e EN, capi in M09 e P09",
    "sch.tmc.r6": "TX verso la UART, serie con i capi in L10 e P10",
    "sch.tmc.r7": "RX dalla stessa UART, diretto",
    "sch.tmc.n1": "LA MASSA NON PASSA DA QUI. Il GND del driver (I02) e il GND dello XIAO (B08)",
    "sch.tmc.n2": "partono entrambi dal nodo, il negativo di C1 (S02), con un filo per ciascuno.",
    "sch.tmc.n3": "Collegarli fra loro chiuderebbe l'anello che pcb/README dice di non chiudere.",
    "sch.tmc.n4": "MS1 e MS2 del driver vanno alla sua massa logica, dentro il suo ramo.",
    "sch.as.title": "Collegamenti XIAO · AS5600 e LED",
    "sch.as.desc": ("I collegamenti fra lo XIAO, il modulo del sensore e il LED di stato. "
                    "Fori nella griglia stampata sulla basetta."),
    "sch.as.right": "AS5600 (J4) e LED (J5)",
    "sch.as.r1": "alimentazione del modulo, 3,3 V",
    "sch.as.r2": "massa del sensore: ramo del bus logico",
    "sch.as.r3": "dato I²C",
    "sch.as.r4": "clock I²C",
    "sch.as.r5": "comando del LED, serie con i capi in G10 e K10",
    "sch.as.r6": "ritorno del LED: stesso ramo logico",
    "sch.as.n1": "Queste due masse partono dal GND dello XIAO e non dal nodo: sono il suo ramo",
    "sch.as.n2": "del bus logico, e dentro un ramo le masse si possono toccare.",
    "sch.as.n3": "Il condensatore da 104 del modulo sta sotto la sua basetta, non qui.",
    "sch.as.n4": "CAVO DEL SENSORE (CAT5), quattro fili, colori come saldati sul modulo: marrone 3V3,",
    "sch.as.n5": "bianco-marrone GND, blu SDA, verde SCL. DIR è a massa sul modulo (ponticello pad 2 - pad 1),",
    "sch.as.n6": "non attraverso il cavo. Tagliati corti e isolati da questo capo: {free}.",
    "sch.pow.title": "Potenza · TMC2209, morsettiere, motore e nodo di massa",
    "sch.pow.desc": ("Le quattro fasi, il ramo dei 12 V e la massa a stella. Non è un diagramma a blocchi ma "
                     "un ELENCO DI FILI: le due colonne sono i due capi, e un componente sta all'una o "
                     "all'altra a seconda del filo. Fori nella griglia stampata sulla basetta."),
    "sch.pow.left": "da questo capo",
    "sch.pow.right": "a quest'altro",
    "sch.pow.r1": "fase A+, filo nero",
    "sch.pow.r2": "fase A−, filo verde",
    "sch.pow.r3": "fase B+, filo rosso",
    "sch.pow.r4": "fase B−, filo blu",
    "sch.pow.r5": "VM al + di C1: reoforo CORTO, è l'anello che conta",
    "sch.pow.r6": "dal + di C1 al + del morsetto 12 V",
    "sch.pow.r7": "C2 in parallelo sull'ingresso, opzionale",
    "sch.pow.r8": "GND di potenza al − di C1: reoforo CORTO",
    "sch.pow.r9": "dal nodo al − del morsetto: primo filo della stella",
    "sch.pow.r10": "dal nodo al GND logico del driver: secondo filo",
    "sch.pow.r11": "dal nodo al GND dello XIAO: terzo filo",
    "sch.pow.n1": "IL NODO DI MASSA È IL NEGATIVO DI C1, IN S02, e da lì partono TRE FILI E SOLO TRE.",
    "sch.pow.n2": "Nessun ramo si collega a un altro ramo: due masse che si toccano in due punti chiudono",
    "sch.pow.n3": "un anello, e parte del ritorno del motore se ne va per la calza dell'USB fino in camera.",
    "sch.pow.n4": "I due reofori di C1 vanno tagliati corti, a cavallo dei pin VM e GND dello zoccolo:",
    "sch.pow.n5": "l'area di quell'anello conta più di qualunque schermatura a valle, e viene prima",
    "sch.pow.n6": "dell'ingombro. È il motivo per cui C1 è rimasto qui e si è spostato C2.",
    "sch.pow.n7": "I colori delle fasi sono quelli del motore, non una scelta: nero e verde una fase,",
    "sch.pow.n8": "rosso e blu l'altra. Scambiare i due fili di UNA fase inverte il verso di rotazione.",
    # --- the sensor cable colours --------------------------------------------
    "col.brown": "marrone",
    "col.white-brown": "bianco-marrone",
    "col.blue": "blu",
    "col.green": "verde",
    "col.white-green": "bianco-verde",
    "col.white-blue": "bianco-blu",
    "col.orange": "arancio",
    "col.white-orange": "bianco-arancio",
    # --- the printed booklet --------------------------------------------------
    "pdf.title": "Wheelly · disposizione e collegamenti",
    "pdf.p1": "Basetta · dove sta ogni componente",
    "pdf.p2": "Basetta · i fili visti da sopra e da sotto",
    "pdf.p3": "Basetta · la massa a stella e l'elenco dei fili",
    "pdf.p4": "Collegamenti · driver, sensore e LED",
    "pdf.footer": "Wheelly · generato dal modello il {date} · pagina {n} di {tot}",
    "pdf.p5": "Collegamenti · potenza, fasi e nodo di massa",
}
