# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: 2026 Matteo Beretta
# SPDX-License-Identifier: CERN-OHL-P-2.0
"""Italian texts of the parameters editor (ui.py), of the dimension chains
it shows and of the assembly plan drawn in it. Same keys as texts_editor_en.py:
texts_editor.py stops if they differ."""

TEXTS = {
    # --- the page of the parameters editor ---
    'ui.title': 'Wheelly — parametri',
    'ui.h1': 'parametri',
    'ui.reset': 'Azzera',
    'ui.changes': 'Modifiche',
    'ui.make_step': 'Genera gli STEP',
    'ui.export': 'Esporta parameters_local.py',
    'ui.search': 'Cerca per nome o descrizione…',
    'ui.f_mod': 'modificati',
    'ui.f_mod_tip': 'Solo i parametri che hai cambiato',
    'ui.f_s': 'solo S',
    'ui.f_s_tip': 'Solo le scelte di progetto, quelle liberamente modificabili',
    'ui.leg_m': 'M misurata sul pezzo',
    'ui.leg_s': 'S scelta di progetto',
    'ui.leg_d': 'D derivata',
    'ui.leg_r': 'R da catalogo',
    'ui.zoom_out': 'Allontana',
    'ui.zoom_in': 'Avvicina',
    'ui.to_dim': 'quota',
    'ui.to_dim_tip': 'Inquadra la quota selezionata',
    'ui.fit': 'adatta',
    'ui.fit_tip': 'Rimetti tutto il disegno nel riquadro',
    'ui.chains': 'Catene dimensionali',
    'ui.cad_title': 'Solidi STEP e verifica completa',
    'ui.regenerate': 'Rigenera',
    'ui.publish': 'Porta i file in out/',
    'ui.close': 'Chiudi',
    'ui.copy': 'Copia',
    'ui.origin_S': 'scelta di progetto — modificabile liberamente',
    'ui.origin_M': 'misurata sul pezzo — si cambia solo rimisurando',
    'ui.origin_D': 'derivata — si cambia il parametro da cui discende',
    'ui.origin_R': 'da catalogo — viene dal datasheet del componente',
    'ui.n_changed_1': '1 parametro modificato',
    'ui.n_changed': '{n} parametri modificati',
    'ui.gen_failed': 'generazione fallita',
    'ui.n_fail_1': '1 controllo non passa',
    'ui.n_fail': '{n} controlli non passano',
    'ui.all_pass': 'tutti i controlli passano',
    'ui.no_match': 'Nessun parametro corrisponde.',
    'ui.not_drawn': 'Questa quota non compare in nessun disegno generato: sta in <b>{where}</b>.',
    'ui.no_drawing': 'Disegno non disponibile.',
    'ui.no_checks': 'Nessun controllo eseguito.',
    'ui.not_traceable': '<b>{name}</b> non è rintracciabile in questo disegno',
    'ui.kind_diametro': 'diametro',
    'ui.kind_raggio': 'raggio',
    'ui.kind_interasse': 'interasse',
    'ui.kind_lunghezza': 'lunghezza',
    'ui.kind_distanza': 'distanza dal centro',
    'ui.kind_ascissa': 'scostamento in X',
    'ui.kind_ordinata': 'scostamento in Y',
    'ui.kind_spessore': 'spessore',
    'ui.kind_other': 'riscontro',
    'ui.from_drawing_n': ' in {n} punti (dal disegno)',
    'ui.from_drawing': ' (dal disegno)',
    'ui.unverified_1': ' &middot; <i>non verificato: un punto vale questo numero, ma il disegno non dice che sia il suo</i>',
    'ui.too_many': ' &middot; <i>questo valore torna in {n} punti del disegno: troppi perché voglia dire qualcosa</i>',
    'ui.ambiguous': " &middot; <i>{n} punti valgono questo numero: quale sia il suo, l'editor non lo sa</i>",
    'ui.lang': 'it',
    'ui.generating': 'Generazione…',
    'ui.diff_title': 'Modifiche rispetto al file sul disco',
    'ui.export_title': 'scostamenti dalla base — salvali in src/parameters_local.py',
    'ui.copied': 'Copiato',
    'ui.expr_mismatch': "L'espressione varrebbe {calc}, il file dice {file}.",
    'ui.saved': '{n} file salvati in out/',
    'ui.old_removed': ' — {n} vecchi rimossi',
    'ui.generated': '{n} file generati',
    'ui.pill_chains': '{n} catene dimensionali',
    'ui.pill_audit': '{n} controlli di audit',
    'ui.pill_fail': ' — {n} non passano',
    'ui.pill_all_pass': ' — tutti passano',
    'ui.published': '{n} file in out/',
    'ui.published_removed': ', {n} rimossi',
    'ui.unsaved': 'Generati con {n} parametri non ancora salvati su <b>src/parameters.py</b>: ',
    'ui.unsaved_tail': ". Porta i file in <b>out/</b> solo se esporti anche i parametri, altrimenti l'audit di build.py troverà la divergenza.",
    # --- the names of the drawings, on the tabs ---
    'tab.assembly_plan': 'insieme · pianta',
    'tab.assembly_section': 'insieme · sezione',
    'tab.assembly_details': 'insieme · dettagli 4:1',
    'tab.body_dimensioned': 'corpo quotato',
    'tab.flat_gasket': 'guarnizione piana',
    'tab.magnet_cap': 'coperchio del magnete',
    'tab.arm_plan': 'pianta braccio',
    'tab.collar_plan': 'pianta collare',
    'tab.sensor_bracket': 'staffa del sensore',
    'tab.collar_section': 'sezione collare',
    'tab.clutch_section': 'sezione frizione',
    # --- the callouts of the assembly plan (drawings_assembly.plan) ---
    'plan.wheel_body': 'corpo ruota (riferimento)',
    'plan.filter_disc': 'disco portafiltri (riferimento)',
    'plan.optical': 'ingombro ottico',
    'plan.magnet': 'magnete AS5600 (lato telescopio)',
    'plan.sensor_board': 'basetta AS5600',
    'plan.bracket': 'staffa del sensore (lato telescopio)',
    'plan.collar_screws': 'M3 del collare e della staffa',
    'plan.collar': 'collare',
    'plan.head': 'scatola, testa piana: USB e GX12',
    'plan.board': 'basetta 30x70 (stima) su pannellino',
    'plan.xiao': 'XIAO ESP32-S3',
    'plan.driver': 'TMC2209 con dissipatore',
    'plan.mech': 'scatola - vano meccanico',
    'plan.clutch': 'frizione',
    'plan.motor': 'motore NEMA14',
    'plan.arm': 'braccio portamotore',
    'plan.spring': 'molla di precarico',
    'plan.spring_cup': 'scodellino della molla',
    'plan.pivot': 'perno 5 + 2 cuscinetti F695ZZ',
    'plan.leg_print': 'pezzi da stampare',
    'plan.leg_ref': 'riferimento: non si stampa',
    'plan.leg_bought': 'componenti comprati',
    # --- the assembly section (drawings_assembly.section); the names it shares
    #     with the plan (wheel body, collar, clutch, arm, motor, legend) use
    #     the plan's keys ---
    'sec.face_camera': 'faccia lato camera',
    'sec.mid_plane_disc': 'piano medio disco',
    'sec.face_telescope': 'faccia lato telescopio',
    'sec.filter_disc': 'disco portafiltri',
    'sec.magnet_board': 'magnete + basetta AS5600',
    'sec.bracket_ring': 'staffa del sensore (anello sul magnete)',
    'sec.gasket_groove': 'cava guarnizione r{r}',
    'sec.labyrinth_rib': 'costola di labirinto nella scanalatura',
    'sec.spring_off_plane': 'molla (fuori piano)',
    'sec.pivot_off_plane': 'perno (fuori piano)',
    'sec.box': 'scatola',
    # --- the scaled details (drawings_assembly.details) ---
    'det.title_a': 'A - appoggio del motore sul braccio (4:1)',
    'det.shaft': 'albero',
    'det.centring_seat': 'sede di centraggio',
    'det.leadin_45': 'invito a 45 gradi, libera il raccordo',
    'det.motor_hub': 'mozzo del motore, col raccordo misurato',
    'det.motor_flange_rests': 'qui appoggia la flangia del motore',
    'det.title_b': 'B - il giunto del perno (4:1)',
    'det.spotface': 'lamatura, fa posto alla flangia',
    'det.setback_face': 'faccia arretrata: non tocca il braccio',
    'det.flange_only_rubs': 'flangia: a strisciare c\'è solo lei',
    'det.two_bearings': 'due F695ZZ, le flange in fuori',
    'det.collar_pivot': 'perno del collare',
    # --- the dimension chains (check_dimensions.py) ---
    'chk.wall_sum': 'somma pareti+apertura = H_body (errore)',
    'chk.disc_in_opening_top': 'disco dentro apertura, sopra',
    'chk.disc_in_opening_bottom': 'disco dentro apertura, sotto',
    'chk.tread_in_knurled_band': 'battistrada nella fascia zigrinata',
    'chk.hub_in_opening_top': 'mozzo dentro apertura, sopra',
    'chk.hub_in_opening_bottom': 'mozzo dentro apertura, sotto',
    'chk.shaft_grip_in_hub': 'presa albero nel mozzo',
    'chk.centre_distance': 'interasse = R_disc + D_clutch/2 (errore)',
    'chk.clutch_hub_vs_inner_wall': 'mozzo frizione vs parete interna',
    'chk.clutch_shoulders_vs_disc_rim': 'spalle frizione vs bordo disco',
    'chk.shoulder_below_tread': 'mozzo frizione: spalla sotto il battistrada',
    'chk.shoulder_above_tread': 'mozzo frizione: spalla sopra il battistrada',
    'chk.grub_collar_outside_body': 'collare del grano fuori dal corpo',
    'chk.grub_collar_under_screw_heads': 'collare del grano sotto le teste delle viti del motore',
    'chk.grub_insert_height': "quota dell'inserto del grano coerente (errore)",
    'chk.motor_inner_corner_outside_body': 'spigolo interno motore fuori dal corpo',
    'chk.motor_holes_vs_arm_rim': 'fori M3 motore vs bordo braccio',
    'chk.motor_outer_corner_vs_box_wall': 'spigolo esterno motore vs parete scatola',
    'chk.clutch_rim_vs_box_wall': 'bordo frizione vs parete scatola',
    'chk.board_inside_box_wall': 'basetta 30x70 dentro la parete scatola',
    'chk.half_chord_vs_clutch_radius': 'semicorda apertura vs raggio frizione',
    'chk.disc_rim_proud_of_flat': 'bordo disco sporge dal piatto',
    'chk.clutch_clear_of_flat': 'frizione non tocca il piatto del taglio',
    'chk.window_half_width': 'semiampiezza finestra coerente col gioco (errore)',
    'chk.r_pivot_consistent': 'R_pivot coerente con la perpendicolare (errore)',
    'chk.l_arm_consistent': 'L_arm coerente (errore)',
    'chk.arm_axis_min_radius': 'raggio minimo asse braccio vs bordo interno',
    'chk.pivot_hub_vs_body': 'mozzo perno vs superficie corpo',
    'chk.preload_consistent': 'precarico di progetto coerente (errore N)',
    'chk.spring_force_margin_on_measured': 'forza delle molle sul bisogno misurato (x)',
    'chk.motor_torque_margin': 'margine coppia motore (tenuta/richiesta)',
    'chk.spring_force_consistent': 'forza molla coerente (errore N)',
    'chk.box_wall_past_moving_parts': 'parete scatola oltre i pezzi mobili',
    'chk.collar_reaches_box_end': 'collare arriva fin dove arriva la scatola',
    'chk.board_cut_past_column_c0': 'basetta tagliata oltre la colonna C0',
    'chk.box_end_consistent': 'fine della scatola coerente con la testa (errore)',
    'chk.front_ear_b_consistent': 'orecchia anteriore B coerente con la testa (errore)',
    'chk.collar_flange_vs_rotator': 'flangia collare vs ingombro rotatore',
    'chk.collar_covers_box': 'collare copre tutta la scatola',
    'chk.gasket_below_groove_bottom': 'guarnizione sotto il fondo della scanalatura',
    'chk.gasket_inside_m3_screws': 'guarnizione dentro le viti M3',
    'chk.gasket_outside_inner_flange': 'guarnizione fuori dalla flangia interna',
    'chk.labyrinth_rib_outside_groove': 'costola di labirinto fuori dalla cava',
    'chk.spring_fitted_shorter': 'molla montata più corta della libera',
    'chk.compression_within_45': 'compressione entro il 45% della lunghezza libera',
    'chk.bearing_seat_through': 'sede cuscinetti passante (flange fuori)',
    'chk.bracket_ring_clearance_magnet': 'gioco anello staffa sul magnete',
    'chk.bracket_ring_clear_of_pivot': 'anello staffa libero dal perno',
    'chk.web_ring_to_m2_holes': 'setto fra anello staffa e fori M2',
    'chk.foot_centres_module': 'il piedino centra ancora il modulo sul magnete',
    'chk.magnet_clearance_printed_hole': 'gioco del magnete nel foro stampato della staffa',
    'chk.air_gap_within_3': 'traferro geometrico entro 3 mm',
    'chk.air_gap_over_05': 'traferro geometrico oltre 0,5 mm',
    'chk.bracket_inside_collar_rim': 'staffa dentro il bordo esterno del collare',
    'chk.paddle_on_bottom_screw': 'paletta {n} della staffa su una vite del fondello',
    'chk.bracket_in_rotator_only_boss': 'staffa nel rotatore solo col mozzetto',
    'chk.paddles_inside_collar_arc': "palette dentro l'arco del collare",
    'chk.bracket_step_outside_board': 'gradino della staffa fuori dalla basetta',
    'chk.board_pad_past_components': 'pad della basetta oltre i componenti',
    'chk.material_m2_hole_to_pad_edge': 'materiale fra foro M2 e bordo del pad',
    'chk.material_beside_m2_hole': 'materiale di fianco al foro M2 nel pad',
    'chk.pad_reaches_past_screw': 'il pad arriva oltre la vite',
    'chk.recess_floor_material': 'fondo dello scasso, materiale che resta',
    'chk.recess_taller_than_components': 'scasso più alto del componente più alto',
    'chk.m2_screw_through_board': 'la vite M2 passa nella basetta',
    'chk.leadin_narrower_than_m2': 'invito più stretto della vite M2',
    'chk.leadin_not_too_narrow': 'invito non troppo stretto',
    'chk.m2_not_below_boss': 'la vite M2 non sbuca sotto il mozzetto',
    'chk.m2_not_below_lowest_foot': 'la vite M2 non sbuca sotto il piedino più basso',
    'chk.m2_grip_in_boss': 'presa della vite M2 nel mozzetto',
}
