# SPDX-FileCopyrightText: 2026 Matteo Beretta
# SPDX-License-Identifier: CERN-OHL-P-2.0
"""Italian catalogue for the chapter 'arm-bearings-and-pivot'."""

CATALOGUE = {
    'arm-bearings-and-pivot/title': ('2c4cf600',
        'Braccio, cuscinetti e perno'),
    'arm-bearings-and-pivot/intro': ('16845760',
        "Il braccio porta il motore e lo lascia oscillare contro la molla, quindi tutta la forza della frizione passa da questo snodo. Gira su due cuscinetti piantati nel braccio, che corrono sul perno in cui hai messo l'inserto nel capitolo {cap_heat_set_inserts}. Qui niente va stretto: lo snodo deve girare senza il minimo sforzo."),
    'arm-bearings-and-pivot/tool1': ('dc57ef8a',
        'chiave a brugola da 2,5 mm'),
    'arm-bearings-and-pivot/tool2': ('c08f8920',
        'una superficie piana e pulita contro cui premere i cuscinetti'),
    'arm-bearings-and-pivot/tool3': ('a39cfd96',
        'un cacciavite, per comprimere la molla di precarico'),
    'arm-bearings-and-pivot/1/title': ('b0bcb233',
        'Pianta i due cuscinetti nel braccio'),
    'arm-bearings-and-pivot/1/point1': ('c37454e1',
        "La sede nel braccio è passante, profonda {sp_braccio} mm: esattamente due cuscinetti F695ZZ da {cusc} mm uno sull'altro."),
    'arm-bearings-and-pivot/1/point2': ('36336c9e',
        "Mettili **con la flangia verso l'esterno**: uno per faccia, così le due flange restano fuori e le facce lisce si incontrano in mezzo."),
    'arm-bearings-and-pivot/1/point3': ('593cab13',
        "La sede è disegnata Ø{sede_cusc} mm perché esca stampata Ø13. Premi a mano, o fra due ganasce piane: mai martellare sull'anello interno."),
    'arm-bearings-and-pivot/1/point4': ('39abd4d8',
        "!Premi solo sull'anello esterno. Un cuscinetto piantato battendo sull'anello interno sembra a posto, e poi gira ruvido per sempre."),
    'arm-bearings-and-pivot/2/title': ('91ca1b7e',
        'Rondella e vite sul braccio, sul banco'),
    'arm-bearings-and-pivot/2/point1': ('72d04b34',
        "La rondella stampata porta il perno: una bussola Ø{d_perno:.0f} mm lunga {perno_lungo:.0f} mm. Infilala attraverso tutti e due i cuscinetti dalla faccia con i quattro fori del motore - il lato camera - finché la rondella non appoggia sull'anello interno del cuscinetto più vicino."),
    'arm-bearings-and-pivot/2/point2': ('949ec5f1',
        'Infila la vite {vite_perno} nella rondella e nella bussola. Tienila indietro con un dito, così che la punta non sporga dalla bussola: la si avvita a fondo quando il braccio è sul perno.'),
    'arm-bearings-and-pivot/3/title': ('cb8bae55',
        "Il braccio dentro dall'apertura dell'elettronica"),
    'arm-bearings-and-pivot/3/point1': ('fd520a5e',
        "Capovolgi il pezzo, lato camera in su. Il braccio entra dal basso, dalla grande apertura nel fondo che poi chiuderà il pannellino della scheda - l'apertura dell'elettronica - con la rondella e la vite già montate, tenendo la vite indietro."),
    'arm-bearings-and-pivot/3/point2': ('7d7967b7',
        "Entra **dalla parte del perno**, poi l'estremità del motore segue verso la botola mentre il braccio si mette in piano: la figura mostra da dove arriva."),
    'arm-bearings-and-pivot/3/point3': ('2cd41088',
        'Aiutandoti con un cacciavite comprimi la molla di precarico e infilala nella sede del braccio.'),
    'arm-bearings-and-pivot/3/point4': ('d50ef0ae',
        'Porta la bussola sotto lo spianamento tondo in cima al perno. Il braccio va in un verso solo: la faccia piana con i quattro fori del motore guarda verso il lato camera.'),
    'arm-bearings-and-pivot/4/title': ('4608ae33',
        'Avvita la vite nel perno'),
    'arm-bearings-and-pivot/4/point1': ('2d3e0fd8',
        "Avvita la vite {vite_perno} attraverso la bussola nell'inserto in fondo al perno, dal lato camera."),
    'arm-bearings-and-pivot/4/point2': ('df61da70',
        'La bussola è lunga esattamente quanto i cuscinetti più una flangia: la vite la tira contro il collare, non contro i cuscinetti, così il braccio gira anche a vite serrata.'),
    'arm-bearings-and-pivot/4/point3': ('010b3d48',
        'Stringi finché la rondella non è ferma, non di più. Poi controlla: il braccio deve oscillare con la punta di un dito e non avere nessun gioco.'),
    'arm-bearings-and-pivot/4/point4': ('3f6162c7',
        'Sopra il braccio ci sono {franco_braccio} mm di luce fino al collare, ed è quello spazio che gli evita di strisciare mentre oscilla. Se il braccio si impunta in qualche punto della corsa, la vite è troppo stretta o manca la rondella.'),
}
