# SPDX-FileCopyrightText: 2026 Matteo Beretta
# SPDX-License-Identifier: CERN-OHL-P-2.0
"""Italian catalogue for the chapter "The board in its panel"."""

CATALOGUE = {
    'board-in-its-panel/title': ('b1df9248',
        "La basetta nel pannellino"),
    'board-in-its-panel/intro': ('75dea9e8',
        "L'elettronica sta su un pezzo di basetta millefori avvitato al pannellino che chiude il lato inferiore della scatola. Basetta e pannellino escono insieme, in un pezzo solo: è così che arrivi a un XIAO o a un driver quando la macchina è già sul telescopio. In questo capitolo la basetta va nel pannellino; cosa va dove sulla basetta non lo ripetiamo qui: il libretto dei collegamenti in `pcb/` è disegnato per chi ha la millefori in mano e il saldatore caldo."),
    'board-in-its-panel/tool1': ('9cda2403',
        "saldatore"),
    'board-in-its-panel/tool2': ('4d98f629',
        "una punta da Ø{foro_basetta_M25} mm, per il foro B05 della basetta millefori"),
    'board-in-its-panel/tool3': ('fbc9886c',
        "chiave a brugola da {chiave_M25} mm, per la vite M2,5"),
    'board-in-its-panel/tool4': ('86d26281',
        "un cacciavite PH0 per le viti M2 svasate"),
    'board-in-its-panel/1/title': ('459509ae',
        "Prima costruisci la basetta, sul banco"),
    'board-in-its-panel/1/point1': ('06e7401d',
        "La basetta è un pezzo di millefori a passo 2,54 mm da {perfboard} mm, {fori_basetta} fori, tagliato a misura con due lati spianati."),
    'board-in-its-panel/1/point2': ('dd7cd006',
        "!Un foro va allargato prima di saldare qualunque cosa, finché la basetta è ancora nuda: **B05** - seconda colonna dal lato della testata, riga 05, fra le due file di piedini dello XIAO - passa dal Ø{fori_stampati_basetta} mm della griglia stampata a Ø{foro_basetta_M25} mm. È il foro della terza vite, e una M2,5 nella griglia così com'è non passa. Adesso è molto più facile che con i componenti montati."),
    'board-in-its-panel/1/point3': ('c2d69aee',
        "Cabla come mostra il libretto in `pcb/`. Salda gli **zoccoli**, non i moduli: XIAO e driver devono poter uscire di nuovo, e il giorno che uno dei due si guasta non vuoi un saldatore vicino al telescopio."),
    'board-in-its-panel/1/point4': ('95f031c9',
        "Tieni bassi i componenti alti. Fra la basetta e il tetto del vano ci sono {sopra_basetta:.1f} mm di spazio, e non uno di più."),
    'board-in-its-panel/1/point5': ('ba909836',
        "!Finisci tutta la basetta adesso e provala sul banco, alimentata dalla USB, prima di metterla nella macchina. Finché è sul tavolo arrivi dappertutto; dopo, quasi da nessuna parte."),
    'board-in-its-panel/2/title': ('2764e309',
        "Cala la basetta nel pannellino e avvitala"),
    'board-in-its-panel/2/point1': ('ac214ef2',
        "Avvita la basetta **prima** di montare XIAO e driver: la {vite_basetta_M25} dal lato della testata sta sotto lo XIAO, e con il modulo al suo posto non ci arrivi più."),
    'board-in-its-panel/2/point2': ('43945613',
        "La basetta **entra dall'alto**, fra le due guide lisce che la mettono in squadra, e si appoggia sulle tre colonnine in cui hai piantato gli inserti al capitolo {cap_heat_set_inserts}."),
    'board-in-its-panel/2/point3': ('c2231537',
        "Due viti svasate {vite_basetta_M2} dal lato largo, nei due fori stampati; una {vite_basetta_M25} dal lato della testata, nel foro che hai allargato a Ø{foro_basetta_M25} mm, con la chiave a brugola da {chiave_M25} mm. Non sono intercambiabili."),
    'board-in-its-panel/2/point4': ('bdbaf0ec',
        "!Le guide mettono in squadra la basetta, non la tengono giù: non forzarla di lato sotto di loro. Un pannellino precedente aveva un labbro che copriva il bordo della basetta, e si è rotto."),
    'board-in-its-panel/3/title': ('6f88b372',
        "Innesta lo XIAO e il driver"),
    'board-in-its-panel/3/point1': ('2454da22',
        "Lo XIAO ESP32-S3 entra nelle sue due file di zoccoli, con la porta USB verso il lato della testata."),
    'board-in-its-panel/3/point2': ('96b025bc',
        "Il driver TMC2208 entra nel suo zoccolo, in piedi."),
    'board-in-its-panel/3/point3': ('ef54318c',
        "!Prima di spingerli a fondo, controlla l'orientamento di tutti e due sul libretto. Un driver montato al contrario è l'unico errore, qui, che brucia qualcosa."),
}
