# SPDX-FileCopyrightText: 2026 Matteo Beretta
# SPDX-License-Identifier: CERN-OHL-P-2.0
"""Italian texts of the chapter 'first-checks'."""

CATALOGUE = {
    'first-checks/title': ('59f3cb61',
        "Prime verifiche"),
    'first-checks/intro': ('b250e5e6',
        "Tutto quello che segue si fa al banco, con la macchina sul tavolo e niente avvitato a un telescopio. L'ordine conta, e non solo perché ogni verifica dà per buona la precedente: ognuna **isola una cosa sola**. Quando qualcosa non va, vuoi avere davanti una causa possibile e non tre: con tre ci passi la serata, e questo progetto una serata così l'ha già spesa."),
    'first-checks/tool1': ('474680c4',
        "un cavo USB-C"),
    'first-checks/tool2': ('68dcf3c0',
        "l'alimentatore da 12 V col suo cavo GX12"),
    'first-checks/tool3': ('ee15ddb7',
        "chiave a brugola da {chiave_precarico} mm, se il precarico va ritoccato"),
    'first-checks/1/title': ('2b7a0358',
        "Prima di alimentare, a occhio e col grano del precarico"),
    'first-checks/1/point1': ('7892e263',
        "!Il disco non si gira più dal suo bordo: la frizione ora riempie la finestra da cui sporgeva il bordo zigrinato. Si gira attraverso la frizione - un pollice sul battistrada (meglio usando un guanto, per non lasciare grasso), nell'incavo sul retro della scatola che l'ultimo passo chiude - ed è quello che usa il passo 3. Questo primo passo non chiede di girare niente."),
    'first-checks/1/point2': ('b9f5a9ce',
        "Guarda nella fessura fra collare e ruota, tutto intorno: la ruota deve essere in battuta sulla flangia dappertutto, con una fessura uniforme."),
    'first-checks/1/point3': ('cebd83ad',
        "Guarda la staffa del sensore di fianco. Fra il suo tampone, sotto il coperchio, e la faccia del disco si deve vedere luce."),
    'first-checks/1/point4': ('68f53e01',
        "L'unica cosa mobile che raggiungi ancora è il precarico. Svita il grano {grano_precarico} finché la molla non è scarica, poi riavvitalo fin dov'era, sentendo il punto in cui la molla comincia a caricarsi. Deve scorrere liscio per tutta la corsa: se gratta o va a scatti, il braccio si impunta sul perno, e conviene aprire la scatola adesso piuttosto che su una montatura al buio."),
    'first-checks/4/title': ('ee9dab40',
        "Ora i 12 V: il chip del driver, prima che giri qualcosa"),
    'first-checks/4/point1': ('f63e8ae3',
        "Collega i 12 V. Poi `cd firmware && ./flash.sh driver_test` chiede alla scheda che cosa vede, che è più veloce di un multimetro e sbaglia meno spesso."),
    'first-checks/4/point2': ('4969323f',
        "Risponde a due domande. La prima: **la UART a filo singolo fa eco?** Escono quattro byte e devono tornare indietro tali e quali, perché TX e RX sono uniti attraverso la resistenza da 1 kΩ, e questo vale che il chip del driver sia vivo o no. Se l'eco non c'è, il guasto è nel filo o in quella resistenza, e il driver non è ancora nemmeno sospettato."),
    'first-checks/4/point3': ('41838d3f',
        "La seconda: **chi risponde, e a quale indirizzo**. Stampa la versione del silicio: `0x20` è un TMC2208, `0x21` un TMC2209. Il firmware li accetta tutti e due."),
    'first-checks/4/point4': ('c6a457bb',
        "!Da qui in avanti i 12 V devono essere accesi: senza, il chip è semplicemente spento e non dice niente, e quel silenzio non è un risultato."),
    'first-checks/4/point5': ('0f8971cd',
        "!Non staccare mai il motore coi 12 V inseriti: il driver muore all'istante. Il motore si collega prima dell'alimentazione, non dopo."),
    'first-checks/5/title': ('d06be27d',
        "Il motore gira, e le fasi sono accoppiate giuste?"),
    'first-checks/5/point1': ('2fd9c0ae',
        "`./flash.sh motor_test` fa un giro completo in un verso e uno indietro, e a metà di ciascuno legge lo stato del driver."),
    'first-checks/5/point2': ('48b39000',
        "**Guarda l'albero.** Questo passo c'è per un guasto che nessun registro vede: le quattro uscite del driver sono due **coppie**, A con A e B con B, e se il connettore a quattro vie spezza una coppia il motore ronza, si scalda e sta fermo. Per il driver ci sono due bobine collegate, quindi non segnala niente."),
    'first-checks/5/point3': ('0bac8934',
        "Su questo motore le coppie giuste sono **nero+verde** e **rosso+blu**."),
    'first-checks/5/point4': ('0fadd338',
        "Due giri in versi opposti e la parte di potenza è a posto."),
    'first-checks/6/title': ('db307a84',
        "Quanta corrente vuole la tua frizione"),
    'first-checks/6/point1': ('6bd8a513',
        "`./flash.sh torque_test` sale a gradini (150, 200, 250, 300, 350 mA) e a ogni gradino tiene il motore in rotazione per otto secondi, così puoi **frenare la frizione con la mano** e sentire dove smette di slittare."),
    'first-checks/6/point2': ('dfa2b63c',
        "Sei alla ruota e non allo schermo, quindi è il motore a dirti a che gradino è: prima di ognuno dà tanti piccoli **colpetti** quanti è il numero del gradino, da contare a orecchio o con una mano sul disco."),
    'first-checks/6/point3': ('c43c7d68',
        "L'esemplare di riferimento si è fermato a **350 mA**, ed è il valore predefinito del firmware. Alla tua può bastarne meno."),
    'first-checks/6/point4': ('ee90ff3c',
        "!Si ferma apposta sotto i 400 mA di targa del motore. Se all'ultimo gradino la frizione slitta ancora, la risposta non sono gli ultimi cinquanta milliampere: è il **precarico della molla**, perché è quello a fissare la soglia di slittamento, non il motore."),
    'first-checks/6/point5': ('a3eefb50',
        "!A 350 mA il motore consuma circa 7 W mentre si muove. Per i due secondi di un cambio filtro non è niente, perché la corrente di mantenimento è zero e a riposo il motore è rilasciato; col mantenimento attivo sarebbe un altro discorso."),
    'first-checks/3/title': ('98c065be',
        "Solo USB: la scheda si accende e legge l'angolo"),
    'first-checks/3/point1': ('ba79cc47',
        "Collega solo la USB - la presa esce sulla testata della scatola - e lascia spenti i 12 V. Controlla che il LED di stato si accenda."),
    'first-checks/3/point2': ('e885bcb8',
        "Gira piano il disco con un pollice sul battistrada della frizione, nella presa "
        "sul retro della scatola, e guarda l'angolo che riporta il sensore. Deve cambiare "
        "in modo regolare e tornare allo stesso valore sullo stesso filtro, entro una "
        "frazione di grado."),
    'first-checks/3/point3': ('777763f1',
        "!Se la lettura salta o si blocca, fermati: è quasi sempre il magnete, non centrato oppure magnetizzato nello spessore invece che lungo il diametro."),
    'first-checks/7/title': ('2ed039af',
        "Sotto tensione, una posizione alla volta"),
    'first-checks/7/point1': ('2a4509fa',
        "Con i 12 V ancora accesi, chiedi la posizione del filtro successiva. Il disco "
        "deve girare, rallentare e fermarsi nella sua posizione."),
    'first-checks/7/point2': ('0ef07cba',
        "Fai il giro di tutte le posizioni due volte. La ruota prende la via più corta "
        "(il Verso di rotazione del pannello) e si avvicina a ogni posizione in pochi "
        "tratti brevi. Un movimento che invece scappa via dalla meta vuol dire che "
        "l'ordine delle fasi in J1 non è quello che si aspetta il firmware (capitolo "
        "{cap_motor_into_the_clutch}); una posizione che non si raggiunge vuol dire che "
        "il motore si è bloccato o che la frizione slitta: controlla prima di tutto che "
        "il fermo della ruota sia stato tolto davvero (capitolo {cap_the_wheel_body})."),
    'first-checks/7/point3': ('7810f105',
        "È la prima volta che la ruota trova le posizioni da sola, quindi guarda e ascolta per tutto il primo giro."),
    'first-checks/7/point4': ('edbde2fa',
        "Se slitta, avvita il grano del precarico di un quarto di giro alla volta, non di più, e riprova."),
    'first-checks/7/point5': ('c2ca98a7',
        "!La macchina va sul telescopio solo quando tutto questo è passato. Togliere il pannellino sul tavolo è molto più facile che dietro una montatura al buio."),
    'first-checks/8/title': ('bd20f4bd',
        "Girala a mano, poi chiudi la presa"),
    'first-checks/8/point1': ('17904f0d',
        "Trova l'incavo sul retro della scatola, in linea con la frizione. Il battistrada nero della frizione ne sporge di {sporgenza_presa} mm: fallo rotolare col pollice e il disco gira. Poco più di mezzo giro di pollice sposta di un filtro."),
    'first-checks/8/point2': ('1c957236',
        "Usala adesso per controllare a mano quello che hai appena visto sotto tensione, e più avanti ogni volta che filtri o treno ottico vanno puliti col treno smontato."),
    'first-checks/8/point3': ('d905da97',
        "Il coperchio entra **dall'alto**. Le due linguette spesse sotto il suo piede scendono nelle loro tasche in fondo all'incavo, la lingua dal lato della molla scorre giù nella scanalatura della parete di testa, il piano superiore scende nell'apertura sopra il motore e le due linguette tonde piccole nelle tasche del collare. Tutto arriva a filo col tetto della scatola."),
    'first-checks/8/point4': ('8678c870',
        "Fissalo con due viti a brugola {vite_presa} a testa **zigrinata**, una per ciascuna linguetta tonda piccola, negli inserti del collare. Le teste stanno sulle linguette, sopra il tetto della scatola, quindi si girano a mano. Il coperchio avvolge anche la cima della parete curva, e sono le due viti a garantire che resti chiuso."),
    'first-checks/8/point5': ('8dd8e818',
        "Per toglierlo, svita le due viti con le dita (non serve la chiave), poi aggancia con l'unghia l'intaglio che attraversa la sua faccia, quello in linea con la frizione, e tira dritto verso l'alto: la faccia piana superiore dell'intaglio è quella su cui tirare."),
    'first-checks/8/point6': ('2f412631',
        "!Tieni il coperchio montato tutte le volte che non stai girando la ruota a mano. L'apertura dà sulla superficie d'attrito, e la polvere che si posa lì è polvere fra la frizione e il disco."),
    'first-checks/tool4': ('66d35c08',
        "chiave a brugola da {chiave_motore} mm, solo se le viti zigrinate del coperchio sono troppo strette per le dita"),
    'first-checks/2/title': ('358054c0',
        "Le due alimentazioni: quando si accendono i 12 V, e quando si spengono"),
    'first-checks/2/point1': ('ded9484b',
        "La macchina ha due alimentazioni, e fanno cose diverse. La **USB** dal computer fa funzionare la scheda: firmware, sensore, LED di stato. I **12 V**, dal GX12 sulla testata della scatola, alimentano solo il driver del motore e il motore. Tutto quello che la scheda ha da dire, lo dice con la sola USB."),
    'first-checks/2/point2': ('c626bfb9',
        "**Accesi** solo per far girare il motore: dal passo 4 al passo 7 qui, e sul telescopio. Prima la USB e poi i 12 V, come fa il libretto dei collegamenti; l'ordine inverso non danneggia il driver, ma così la scheda è già accesa e in ascolto quando si sveglia la parte del motore."),
    'first-checks/2/point3': ('faa8ab13',
        "!**Spenti** - si stacca il cavo GX12 - prima di collegare o scollegare qualunque cosa dentro la scatola, il motore prima di tutto: un passo-passo staccato da un driver alimentato lo uccide sul colpo. Spenti prima di togliere il pannellino, e spenti quando hai finito: prima i 12 V, poi la USB."),
    'first-checks/2/point4': ('a9353b14',
        "Per girare il disco a mano non serve spegnerli: a riposo il motore è rilasciato, e un pollice sulla frizione lo fa girare. Gira piano. Se hai acceso una corrente di tenuta (Opzioni), togli prima i 12 V, se no lotti contro il motore; e metti il LED su Spento se non vuoi i suoi lampeggi d'allarme - per il firmware un disco mosso a mano è una deriva."),
    'first-checks/7/point6': ('a25bbdf4',
        "Finito: prima spegni i 12 V, poi la USB."),
}
