# SPDX-FileCopyrightText: 2026 Matteo Beretta
# SPDX-License-Identifier: CERN-OHL-P-2.0
"""Italian catalogue for the chapter 'heat-set-inserts'."""

CATALOGUE = {
    'heat-set-inserts/title': ('2a6127a5',
        'Inserti a caldo'),
    'heat-set-inserts/intro': ('a9e6d0b4',
        "Prima di montare qualunque cosa, i pezzi stampati ricevono i loro inserti d'ottone. Farli tutti in una volta non è solo comodità: alcuni si raggiungono solo finché il pezzo è nudo, e l'inserto del perno è il caso più chiaro - una volta che il braccio è appeso a quel perno, nessun saldatore ci arriverà più. Qui va anche l'inserto della frizione, per ultimo."),
    'heat-set-inserts/tool1': ('1f18fc3e',
        'saldatore con le punte per inserti a caldo M2, M2,5, M3 e M4'),
    'heat-set-inserts/tool2': ('be258b08',
        'un blocchetto squadrato su cui fare contrasto, o una mano ferma'),
    'heat-set-inserts/1/title': ('2aed7c0d',
        "Il collare: prima di tutto l'inserto del perno"),
    'heat-set-inserts/1/point1': ('4d31bc3b',
        "Metti il collare davanti a te con il lato del telescopio verso l'alto: è il lato dove sporge il perno."),
    'heat-set-inserts/1/point2': ('19179360',
        "Pianta l'inserto M3 da {inserto_M3} mm nella punta del perno, a filo con la faccia attorno."),
    'heat-set-inserts/1/point3': ('4bada8cf',
        '!Fai questo prima degli altri e prima di montare qualsiasi cosa. Il braccio si appende a questo perno e la vite che lo tiene arriva dal lato opposto: una volta che il collare è sulla ruota, a questo foro non ci torni più.'),
    'heat-set-inserts/1/point4': ('8020ccfc',
        "Tieni il saldatore dritto lungo il perno. Il foro è sull'asse di una colonnina da Ø{d_perno:.0f} mm, e un inserto che entra storto si porta dietro storta anche la vite."),
    'heat-set-inserts/2/title': ('5e17d8df',
        'La scatola: tre inserti per le viti del pannellino'),
    'heat-set-inserts/2/point1': ('df8749f7',
        "La scatola prende tre inserti M3, tutti sulla faccia esterna attorno all'apertura del pannellino."),
    'heat-set-inserts/2/point2': ('e25e42af',
        'Ancora gli stessi inserti da {inserto_M3} mm.'),
    'heat-set-inserts/2/point3': ('533ba4e5',
        'Le viti del pannellino sono svasate e tirano il pannellino piatto contro questa faccia, quindi qui conta che gli inserti finiscano a filo e non sporgenti.'),
    'heat-set-inserts/3/title': ('c1c30068',
        'La scatola: due inserti per la botola del motore'),
    'heat-set-inserts/3/point1': ('e3e4adb1',
        'Altri due inserti M3 da {inserto_M3} mm, sulla faccia esterna del fondo, nelle due tasche accanto alla botola quadrata sotto il motore.'),
    'heat-set-inserts/3/point2': ('afb06300',
        'Entrano da sotto, come quelli del pannellino, e finiscono a filo con il cielo della loro tasca: le due orecchie del coperchio della botola si appoggiano in quelle tasche e le sue viti svasate le tirano piatte.'),
    'heat-set-inserts/4/title': ('80d7e58b',
        "Il collare: l'inserto per la vite del coperchio"),
    'heat-set-inserts/4/point1': ('1e0405f7',
        'Un altro inserto M3 da {inserto_M3} mm, nella piccola tasca tonda sopra il collare, accanto alla grande apertura sopra il motore.'),
    'heat-set-inserts/4/point2': ('27c7c729',
        "Entra dall'alto, dritto in giù, a filo con il fondo della tasca. La linguetta del coperchio si appoggia in quella tasca e la sua vite scende in questo inserto."),
    'heat-set-inserts/5/title': ('e536a0a6',
        "Il collare: l'inserto per la seconda vite del coperchio"),
    'heat-set-inserts/5/point1': ('6ba6a74a',
        "Un secondo inserto M3 da {inserto_M3} mm per il coperchio, nell'altra piccola tasca tonda sopra il collare: quella nell'angolo dove il collare incontra la parete curva attorno al motore, dalla parte opposta all'elettronica."),
    'heat-set-inserts/5/point2': ('d5c4a51d',
        'Dritto in giù come il primo, a filo con il fondo della tasca.'),
    'heat-set-inserts/6/title': ('645a6aaa',
        "La scatola: l'inserto M4 per la vite di precarico"),
    'heat-set-inserts/6/point1': ('8f974568',
        'Nella scatola ne va ancora uno, ed è quello diverso dagli altri: un inserto M4 da {inserto_M4} mm, nella parete esterna dietro la sede della molla.'),
    'heat-set-inserts/6/point2': ('bb357575',
        "Entra **in orizzontale, dall'interno della scatola**, lungo l'asse della molla: il saldatore attraversa il vano dal lato della ruota, passa dal piccolo foro tondo nella parete interna e spinge l'inserto verso la parete esterna. Tieni il saldatore in bolla. (Se la punta per inserti è troppo corta per arrivarci - nella ruota di riferimento lo era quella da 8 mm - usa al suo posto un chiodo, scaldato col saldatore: è così che è entrato questo inserto.)"),
    'heat-set-inserts/6/point3': ('1fdd5aeb',
        "!È l'inserto in cui lavora il grano del precarico, e la molla ci spinge sopra con {forza_N} N per tutta la vita della macchina. Vale il minuto in più che ci vuole per piantarlo in squadra."),
    'heat-set-inserts/7/title': ('33c8b670',
        'Il pannellino: tre piccoli inserti per la scheda'),
    'heat-set-inserts/7/point1': ('1871cbce',
        'Il pannellino prende tre inserti sulla faccia interna, in cima alle colonnine su cui si appoggerà la scheda.'),
    'heat-set-inserts/7/point2': ('5cf50a57',
        'Due sono M2, da {inserto_M2} mm, e quello dal lato della testata è M2,5, da {inserto_M25} mm. Non sono intercambiabili: per quello monta la punta M2,5.'),
    'heat-set-inserts/7/point3': ('5e8a3d55',
        "!Sono piccoli. Lascia lavorare il saldatore e fermati appena l'ottone è a livello della colonnina: una colonnina spinta troppo si fonde e si accorcia, e poi la scheda poggia sul pannellino invece che sulle colonnine."),
    'heat-set-inserts/8/title': ('c0387602',
        'La staffa del sensore: due inserti per il suo coperchio'),
    'heat-set-inserts/8/point1': ('5467316b',
        'Per ultima la staffa del sensore: due inserti M2,5 da {inserto_M25} mm, uno a ciascuna estremità della sede del coperchio.'),
    'heat-set-inserts/8/point2': ('1c59f482',
        'Il coperchio si avvita su questi due e tiene la scheda del sensore contro la staffa, quindi piantali in squadra.'),
    'heat-set-inserts/9/title': ('0d26da30',
        "La frizione: l'inserto M3 per il suo grano"),
    'heat-set-inserts/9/point1': ('af1cd55b',
        "Prendi la frizione stampata, fuori dalla macchina, in mano, e trova il canale sul fianco del mozzo. Va dritto dall'esterno fino al foro dell'albero."),
    'heat-set-inserts/9/point2': ('5f03164c',
        "Spingi l'inserto {inserto} nel canale con la punta M3, dalla parte dell'ottone."),
    'heat-set-inserts/9/point3': ('084daba5',
        "Tieni il saldatore in linea col canale. Il canale è aperto fino all'esterno proprio per questo: le spalle del battistrada arrivano a Ø{d_spalle:.0f} mm, e un saldatore che entra storto finisce su di loro invece che sull'inserto."),
    'heat-set-inserts/9/point4': ('76c717b5',
        "!L'inserto si ferma da solo dove il canale si stringe nel foro di passaggio del grano. Non spingerlo oltre: non c'è modo di tirarlo fuori."),
}
