# SPDX-FileCopyrightText: 2026 Matteo Beretta
# SPDX-License-Identifier: CERN-OHL-P-2.0
"""Italian catalogue for the chapter 'motor-into-the-clutch'."""

CATALOGUE = {
    'motor-into-the-clutch/title': ('9ece7ac3',
        'Il motore, su dentro la frizione'),
    'motor-into-the-clutch/intro': ('39927760',
        "Il motore è l'ultimo pezzo del meccanismo: entra dal basso, dalla botola nel fondo, e il suo albero trova la frizione che lo aspetta già sopra il braccio. Poi si blocca la frizione sull'albero, si mettono le quattro viti del motore dall'alto attraverso i fori della frizione e si chiude la botola."),
    'motor-into-the-clutch/tool1': ('ab609c54',
        'chiave a brugola da {chiave} mm, per il grano della frizione'),
    'motor-into-the-clutch/tool2': ('fefcb387',
        'chiave a brugola da {chiave_motore} mm, per le viti del motore'),
    'motor-into-the-clutch/tool3': ('3f1dd728',
        'un cacciavite PH0, per le viti svasate della botola'),
    'motor-into-the-clutch/1/title': ('d921778c',
        'Porta su il motore dalla botola, dentro la frizione'),
    'motor-into-the-clutch/1/point1': ('671fcbc2',
        "Cablalo prima, sul banco: i suoi quattro fili vanno nella spina di J1, una JST XH a 4 vie, con le coppie una accanto all'altra - **nero+verde** e **rosso+blu**, le coppie che controlla il capitolo {cap_first_checks}. Lasciali abbastanza lunghi da arrivare alla scheda."),
    'motor-into-the-clutch/1/point2': ('a5f0fa41',
        'Prima piega i quattro fili in giù lungo il corpo del motore: passano dalla botola accanto a lui, e sono fili.'),
    'motor-into-the-clutch/1/point3': ('e31d2c92',
        "Gira l'albero finché la spianatura non è allineata con quella nel foro della frizione, che vedi dall'alto."),
    'motor-into-the-clutch/1/point4': ('c85d4736',
        "Da sotto, attraverso la botola, spingi su il motore: l'albero passa nel braccio ed entra nella frizione, e la faccia anteriore del motore va ad appoggiare in piano sul braccio."),
    'motor-into-the-clutch/1/point5': ('0703d2f2',
        "Giralo in modo che i fili escano verso il vano dell'elettronica e i quattro fori sulla faccia del motore siano allineati con quelli del braccio."),
    'motor-into-the-clutch/1/point6': ('347f31de',
        "!Tieni l'ordine del disegno - nero A+, verde A-, rosso B+, blu B-. Il firmware inverte il segnale DIR del motore proprio per quest'ordine: con una fase girata ogni movimento scappa via dalla meta, e allora la correzione va nel firmware (`mechanics_esp32.cpp`), non nei fili che hai già crimpato."),
    'motor-into-the-clutch/2/title': ('11e29b49',
        'Bloccalo col grano'),
    'motor-into-the-clutch/2/point1': ('f49cd7c2',
        "Spingi la frizione giù sull'albero fino in fondo. Gira l'albero a mano finché il foro del grano non guarda il centro del collare: la chiave entra da lì, attraverso il varco nell'anello."),
    'motor-into-the-clutch/2/point2': ('bd2a2f69',
        "Avvita il grano {grano} nell'inserto con una chiave a brugola da {chiave} mm, finché non appoggia sulla spianatura dell'albero."),
    'motor-into-the-clutch/2/point3': ('a5ef0cf1',
        "La sezione mostra quello che da fuori non vedi: la spianatura del foro appoggia già sulla spianatura dell'albero, quindi il grano deve solo tenere giù la frizione. La coppia passa dalle spianature, non dall'attrito."),
    'motor-into-the-clutch/2/point4': ('ab275f1d',
        "!Stringi deciso ma senza caricarci sopra: dal lato sottile l'inserto è tenuto da {parete} mm di ASA."),
    'motor-into-the-clutch/2/point5': ('9d7018f6',
        "Controlla a mano che la frizione non giri sull'albero e non si sfili."),
    'motor-into-the-clutch/3/title': ('014918dc',
        "Quattro viti, dall'alto, attraverso la frizione"),
    'motor-into-the-clutch/3/point1': ('bd428614',
        "Gira la frizione finché i suoi quattro fori non stanno sopra i quattro fori del braccio. Dall'apertura sopra il motore, fai cadere ogni vite {vite_motore} nel suo foro della frizione e avvitala nei filetti del motore con una chiave a brugola da {chiave_motore} mm, passando dallo stesso foro."),
    'motor-into-the-clutch/3/point2': ('f08f40be',
        "Stringile in croce, come le ruote dell'auto: una, poi quella opposta, e tirale giù in modo uniforme. La faccia del motore deve finire in piano sul braccio, perché tutto il lavoro della frizione dipende dall'albero perpendicolare al braccio."),
    'motor-into-the-clutch/3/point3': ('606b1b87',
        '!Non forzarle. Si avvitano nei fori filettati del motore stesso, e oltre il semplice accostamento non si guadagna niente.'),
    'motor-into-the-clutch/4/title': ('25a18312',
        'Chiudi la botola sotto il motore'),
    'motor-into-the-clutch/4/point1': ('a40ae8e6',
        'La botola quadrata nel fondo sotto il motore è da dove entra il motore. Una volta che il motore è sul braccio, chiudila.'),
    'motor-into-the-clutch/4/point2': ('007183ec',
        "Il coperchio entra dal basso, faccia piana verso l'esterno: il bordo appoggia sul gradino attorno alla botola e finisce a filo del fondo."),
    'motor-into-the-clutch/4/point3': ('158a11d9',
        'Fissalo con due viti svasate {vite_botola} passate nelle sue orecchie, negli inserti accanto alla botola - con un cacciavite PH0.'),
}
