# SPDX-FileCopyrightText: 2026 Matteo Beretta
# SPDX-License-Identifier: CERN-OHL-P-2.0
"""Italian catalogue for the chapter parts-tools-and-printing."""

CATALOGUE = {
    'parts-tools-and-printing/title': ('1d013714',
        "Pezzi, attrezzi e stampa"),
    'parts-tools-and-printing/intro': ('6149ec81',
        "Prima di piantare il primo inserto, ecco la macchina intera: tutto ciò di cui è fatta e tutto quello che ti serve sul banco. I colori che vedi qui sono quelli che ogni pezzo tiene per il resto della guida: se in questa figura distingui il braccio dal collare, li distinguerai anche quindici passi più avanti, mezzi nascosti dietro la scatola."),
    'parts-tools-and-printing/tool1': ('0458509b',
        "una stampante 3D e i filamenti: ASA e TPU, di qualunque durezza da 87A a 95A (provato con l'87A, calcolato fino al 95A)"),
    'parts-tools-and-printing/tool2': ('32ea5e0b',
        "saldatore con le punte per inserti a caldo M2, M2,5, M3 e M4, e una punta fine per cablare la basetta"),
    'parts-tools-and-printing/tool3': ('544f771a',
        "una punta da trapano da Ø{foro_basetta_M25} mm, per un foro della millefori"),
    'parts-tools-and-printing/tool4': ('35d0cbdb',
        "chiavi a brugola da 1,5, 2 e 2,5 mm"),
    'parts-tools-and-printing/tool5': ('e78a86fa',
        "un cacciavite PH0 e un cacciavite piatto da 2 mm"),
    'parts-tools-and-printing/tool6': ('7f0921bd',
        "una chiave da 14 mm, per il dado del connettore GX12"),
    'parts-tools-and-printing/tool7': ('136aaf05',
        "un calibro, per controllare quello che esce dal piatto"),
    'parts-tools-and-printing/tool8': ('17c2626c',
        "una fascetta da 2,5 mm per il cavo del sensore"),
    'parts-tools-and-printing/tool9': ('d9b86f80',
        "una goccia di colla per il magnete: cianoacrilato o epossidica"),
    'parts-tools-and-printing/tool10': ('ccf1676d',
        "un computer con Python 3.12 e Chrome o Edge, e un cavo USB-C"),
    'parts-tools-and-printing/tool11': ('1d7eb696',
        "una scheda ESP32 qualsiasi su una breadboard, per regolare il traferro"),
    'parts-tools-and-printing/tool12': ('29e197e0',
        "l'alimentatore da 12 V col suo cavo GX12, per le prime prove"),
    'parts-tools-and-printing/tool13': ('454c7c12',
        "un blocchetto squadrato contro cui premere gli inserti"),
    'parts-tools-and-printing/tool14': ('c08f8920',
        "una superficie piana e pulita contro cui premere i cuscinetti"),
    'parts-tools-and-printing/tool15': ('bf20123c',
        "2 viti M2 × 4, a testa cilindrica o svasata, per i piedini del traferro"),
    'parts-tools-and-printing/tool16': ('34a158f0',
        "un cacciavite adatto alle viti del fermo della ruota"),
    'parts-tools-and-printing/1/title': ('35c8a0ad',
        "Che cosa stai costruendo"),
    'parts-tools-and-printing/1/point1': ('272c2012',
        "Una ruota portafiltri manuale, motorizzata: i pezzi stampati si serrano attorno alla ruota che hai già e si tolgono di nuovo senza tagliare niente. Il progetto è nato attorno a una StarDikor a cinque posizioni per filtri da 2 pollici - è la ruota che vedi in tutte le figure - e per una ruota diversa bastano pochi parametri, non un nuovo progetto."),
    'parts-tools-and-printing/1/point2': ('7750022c',
        "Il motore passo-passo è appeso sotto un braccio che ruota su un perno, e una molla spinge il braccio in modo che la frizione prema sul bordo del disco dei filtri. Tutto il resto - il sensore, la scheda, la scatola - si appoggia su questi pochi pezzi."),
    'parts-tools-and-printing/1/point3': ('d55451e5',
        "**Il corpo della ruota si monta per ultimo**, e il motivo è misurato: sopra la frizione, con la ruota al suo posto, non c'è spazio per imboccarlo sull'albero."),
    'parts-tools-and-printing/2/title': ('434230bc',
        "I pezzi da stampare"),
    'parts-tools-and-printing/2/point1': ('94c86dea',
        "{n_stampati} pezzi stampati: ASA per quelli che restano, TPU per il battistrada e le guarnizioni - di qualunque durezza da 87A a 95A: la macchina è stata provata solo con l'87A, e fino al 95A è calcolata, non provata. Masse e orientamenti di stampa sono nell'elenco qui sopra: l'orientamento fa parte del progetto, non è una scelta lasciata allo slicer."),
    'parts-tools-and-printing/2/point2': ('2719091d',
        "Se stai facendo un prototipo, stampalo prima in PETG: è più facile. Le tolleranze di questo progetto però sono state misurate sull'ASA, quindi un pezzo in PETG può accoppiarsi in modo leggermente diverso."),
    'parts-tools-and-printing/2/point3': ('fd9f0b1c',
        "Qui i pezzi sono mostrati dove finiscono, non disposti sul piatto, e la scatola è disegnata trasparente perché si veda quello che copre. Guarda i colori: da qui in avanti non cambiano più."),
    'parts-tools-and-printing/3/title': ('7b3effbd',
        "E la meccanica che compri"),
    'parts-tools-and-printing/3/point1': ('87e0392e',
        "Il motore, due cuscinetti, il magnete, la molla, le viti e gli inserti - mostrati qui da soli, senza i pezzi stampati attorno, così vedi quanto sono pochi e dove va ciascuno."),
    'parts-tools-and-printing/3/point2': ('fdb85d74',
        "Acciaio per le viti e i cuscinetti, ottone per gli inserti a caldo: due colori, perché nella figura di una macchina sarebbero altrimenti la stessa macchia grigia."),
    'parts-tools-and-printing/3/point3': ('77153780',
        "Anche l'elettronica si compra, ed è nell'elenco qui sopra, sotto la sua voce: qui non ha una figura perché si cabla sul banco prima di incontrare la macchina, al capitolo {cap_board_in_its_panel}."),
    'parts-tools-and-printing/3/point4': ('363cb89e',
        "!Controlla il magnete prima di comprarlo: deve essere **magnetizzato diametralmente**. Quello magnetizzato nello spessore è identico a vederlo, si compra per sbaglio facilmente e al sensore non dà niente da leggere."),
}
