# SPDX-FileCopyrightText: 2026 Matteo Beretta
# SPDX-License-Identifier: CERN-OHL-P-2.0
"""Italian catalogue for the chapter 'sensor-and-closing-up'."""

CATALOGUE = {
    'sensor-and-closing-up/title': ('d87cfca6',
        'Il sensore, e si chiude'),
    'sensor-and-closing-up/intro': ('ccd8fb25',
        "L'arco del sensore si monta per ultimo. Il suo tampone arriva sopra il centro della ruota, a un soffio dalla faccia del disco dei filtri, e il magnete lo guarda da sotto attraverso un foro: per questo non poteva andare su prima della ruota. Collegato il suo cavo alla scheda, il pannellino sale sotto la scatola e la macchina è chiusa."),
    'sensor-and-closing-up/tool1': ('dc57ef8a',
        'chiave a brugola da 2,5 mm'),
    'sensor-and-closing-up/tool2': ('70ddbb29',
        'chiave a brugola da {chiave_M25} mm per le viti del coperchio'),
    'sensor-and-closing-up/tool3': ('510e9c4c',
        'un cacciavite PH0 per le viti svasate del modulo e del pannellino'),
    'sensor-and-closing-up/tool4': ('ab62a67c',
        'una fascetta da 2,5 mm'),
    'sensor-and-closing-up/1/title': ('45fab6c4',
        'La staffa, sopra la ruota e sul collare'),
    'sensor-and-closing-up/1/point1': ('28683da7',
        "Prima di montarla, infila una fascetta da 2,5 mm nel tampone del braccio rivolto verso la scatola: giù da una delle due asole, lungo la scanalatura sotto, su dall'altra. Lasciala aperta. Quando la staffa è appoggiata sulla ruota, sotto il braccio non ci si arriva più: è la scanalatura che fa passare la fascetta senza sollevare la staffa dalla ruota."),
    'sensor-and-closing-up/1/point2': ('20e6505f',
        'Abbassa la staffa finché il tampone scende sopra il magnete e i due piedi si appoggiano sulla flangia del collare.'),
    'sensor-and-closing-up/1/point3': ('cbddf4f0',
        'Viti {vite_collare}, una per piede, attraverso il piede e la flangia del collare che gli sta sotto, nei fori filettati M3 già presenti nel fondello del corpo della ruota, dal lato del telescopio.'),
    'sensor-and-closing-up/1/point4': ('f38de237',
        "!Non forzarla verso il basso. Il tampone passa appena sopra la faccia del disco: se tocca, sotto c'è qualcosa che non è al suo posto, quasi sempre la ruota che non è entrata fino in fondo nel collare."),
    'sensor-and-closing-up/2/title': ('4d12c62d',
        'Il modulo AS5600, sulle sue due viti'),
    'sensor-and-closing-up/2/point1': ('26f8572a',
        "Il modulo AS5600 entra nella sede in cima alla staffa, col chip verso il basso, sopra il foro che guarda il magnete. Fra chip e magnete restano circa {traferro} mm d'aria."),
    'sensor-and-closing-up/2/point2': ('fe08cd59',
        'Fissalo con due viti svasate {vite_modulo}, attraverso i suoi due fori nei fori pilota della staffa, con un cacciavite PH0. Si formano da sole il filetto nella plastica: stringile quanto basta, non di più.'),
    'sensor-and-closing-up/3/title': ('6d6a6b34',
        'Il cavo, poi il coperchio sopra il modulo'),
    'sensor-and-closing-up/3/point1': ('700895ca',
        'Innesta il cavo sul modulo prima di mettere il coperchio: col coperchio chiuso il connettore non si raggiunge più.'),
    'sensor-and-closing-up/3/point2': ('79c8a9e2',
        'Il coperchio va sopra e si fissa con due viti {vite_coperchio} negli inserti M2,5 che hai piantato nella staffa al capitolo {cap_heat_set_inserts}. Appoggia sulla staffa, mai sul modulo: il modulo è tenuto dalle sue due viti.'),
    'sensor-and-closing-up/4/title': ('af34387c',
        'Porta il cavo del sensore giù nella scatola'),
    'sensor-and-closing-up/4/point1': ('063e3e66',
        "Il cavo da {sensor_cable} mm esce dal coperchio lungo il canale aperto nel braccio della staffa (ci si appoggia da sopra, non va infilato in niente) e scende nella scatola dall'apertura nella sua parete."),
    'sensor-and-closing-up/4/point2': ('160552bc',
        'Tienilo morbido: in nessun punto deve piegare con un raggio più stretto di circa {raggio_cavo} mm.'),
    'sensor-and-closing-up/4/point3': ('aab7e310',
        'Chiudi sul cavo la fascetta che avevi infilato sotto il braccio, sulla sede piana fra le due asole, e taglia la coda. È lei a tenere gli strappi sul cavo lontani dalle piazzole saldate della schedina del sensore, il giunto più debole di tutta la catena.'),
    'sensor-and-closing-up/4/point4': ('4c4841c6',
        '!Lascia nella scatola cavo a sufficienza perché il pannellino, quando lo riapri, possa restare appeso ai suoi cavi. Un cavo tagliato alla lunghezza giusta al millimetro è un cavo che strappi la seconda volta che apri.'),
    'sensor-and-closing-up/5/title': ('9936383f',
        'Collega tutto e chiudi il pannellino'),
    'sensor-and-closing-up/5/point1': ('40e50348',
        'Alla scheda arrivano tre cavi: il motore, il sensore, e il connettore col LED nella testata della scatola. Collegali tutti col pannellino ancora libero, dove vedi quello che fai.'),
    'sensor-and-closing-up/5/point2': ('b114d781',
        'Porta il pannellino nel suo gradino sotto la scatola e spingilo in piano. Sta in una battuta, quindi entra in un verso solo.'),
    'sensor-and-closing-up/5/point3': ('edb0078e',
        "Tre viti svasate {vite_pannellino} negli inserti intorno all'apertura. Imboccale tutte e tre, poi stringile insieme."),
    'sensor-and-closing-up/5/point4': ('cd9626ff',
        '!Togli il pannellino e rimettilo una volta, adesso, prima che la macchina vada da qualche parte. Quello che va storto con un coperchio non succede mai la prima volta che si chiude: succede la seconda volta che si apre.'),
}
