# SPDX-FileCopyrightText: 2026 Matteo Beretta
# SPDX-License-Identifier: CERN-OHL-P-2.0
"""Italian catalogue for the chapter "Setting the air gap"."""

CATALOGUE = {
    'setting-the-air-gap/title': ('eb76564f',
        "Regolare il traferro"),
    'setting-the-air-gap/intro': ('f27e2e9a',
        "Il sensore legge un magnete attraverso un traferro di meno di un millimetro, e quel traferro dipende da una sola quota di un solo pezzo stampato: il piedistallo su cui poggia la staffa. Troppo lontano e il campo è troppo debole per leggerlo bene; troppo vicino e il magnete tocca il chip. In questo capitolo l'altezza giusta si trova misurando, non calcolando, perché nella pila da cui dipende c'è anche la colla."),
    'setting-the-air-gap/skip': ('8ef50ef2',
        "Se costruisci sulla stessa ruota attorno a cui è disegnato questo progetto - una ruota portafiltri manuale da {ruota_rif} mm, con il disco rotante da {disco_rif} mm - e con lo stesso magnete diametrale da {magnete_rif} mm, **passa direttamente al capitolo successivo**: la staffa pubblicata ha già l'altezza a cui è arrivata questa procedura. Torna qui solo se le letture del capitolo {cap_first_checks} vengono scarse."),
    'setting-the-air-gap/tool1': ('a12ce865',
        "una scheda ESP32 qualsiasi su una breadboard: non deve per forza essere lo XIAO"),
    'setting-the-air-gap/tool2': ('2bdbc3dc',
        "2 viti M2 × 4, a testa cilindrica o svasata"),
    'setting-the-air-gap/tool3': ('f24ecfdb',
        "un cacciavite a taglio da 2 mm, o quello adatto a quelle teste"),
    'setting-the-air-gap/tool4': ('b6905138',
        "un calibro"),
    'setting-the-air-gap/tool5': ('8fd70b28',
        "Chrome o Edge: la pagina di prova usa Web Serial"),
    'setting-the-air-gap/1/title': ('076e2dce',
        "Perché non si può calcolare"),
    'setting-the-air-gap/1/point1': ('6f2fb231',
        "Secondo il disegno, distanziale e magnete arrivano 1,8 mm sopra la faccia del mozzo. Incollati su un perno vero **misurano 2,3**: mezzo millimetro sparisce fra i due giunti e la tolleranza di stampa del distanziale."),
    'setting-the-air-gap/1/point2': ('24b4f28d',
        "Qui mezzo millimetro non è un dettaglio: senza contarlo la staffa viene bassa proprio di tanto, e il traferro vero era di **0,07 mm**, con il magnete che sfiorava il chip."),
    'setting-the-air-gap/1/point3': ('ae691e4e',
        "Quindi l'altezza si sceglie provando piedini di spessore noto e leggendo cosa dice il sensore. Ci vogliono venti minuti, ed è l'unico modo di tener conto della colla."),
    'setting-the-air-gap/2/title': ('69377e67',
        "Stampa i piedini e il distanziale"),
    'setting-the-air-gap/2/point1': ('0ca9af39',
        "`out/tools/gap_gauges.step` contiene {piedini_n} piedini, alti da {piedini_da} a {piedini_a} mm - traferri da {traferro_da} a {traferro_a} mm - con l'altezza incisa sulla linguetta. `out/magnet_spacer.step` è il distanziale su cui poggia il magnete."),
    'setting-the-air-gap/2/point2': ('15628226',
        "!Nello slicer **non attivare anche la compensazione dei fori**: il foro del magnete è già disegnato maggiorato per tenerne conto, e le due correzioni si sommano."),
    'setting-the-air-gap/2/point3': ('acd37652',
        "Dopo la stampa **misura il foro del magnete col calibro** e dillo al modello: `Comp_hole_printing` è un numero che riguarda la tua stampante, non questo progetto, e da lì in poi vale anche per la staffa vera, che quell'accoppiamento lo vuole stretto."),
    'setting-the-air-gap/2/point4': ('24e1e9fa',
        "Ti servono anche due viti **M2 × 4**, a testa cilindrica o svasata: si fanno il filetto da sole nel foro da 1,8 mm. Quelle più lunghe sporgono dall'altra parte e tengono il piedino sollevato dalla faccia."),
    'setting-the-air-gap/3/title': ('99fa6419',
        "Cabla la schedina del sensore sul banco"),
    'setting-the-air-gap/3/point1': ('728574c9',
        "Per questo va bene qualunque ESP32: un WROOM-32 su una breadboard è perfetto, non serve lo XIAO. Alimenta il modulo AS5600 a **3,3 V**, SDA e SCL ai due piedini I²C, e DIR a massa."),
    'setting-the-air-gap/3/point2': ('f2d26960',
        "!Il modulo deve avere il **ponticello VDD5V-VDD3V3**, e con quel ponticello non sopporta più i 5 V. Prima di dare tensione controlla la continuità fra i piedini 1 e 2 del chip: un ponticello staccato non si fa notare, dimezza in silenzio le letture e sembra in tutto e per tutto un magnete debole."),
    'setting-the-air-gap/3/point3': ('f67a0caa',
        "Carica `firmware/air_gap_test/air_gap_test.ino`: `cd firmware && ./flash.sh air_gap_test`."),
    'setting-the-air-gap/4/title': ('aa4b6585',
        "Leggi sulla pagina, non sul monitor seriale"),
    'setting-the-air-gap/4/point1': ('e912e27e',
        "`cd firmware && ./gap_page.sh` serve il banco di prova su **http://localhost:8770/** e lo apre. Mostra l'AGC in tempo reale, accende i settori del giro man mano che li copri, e tiene la tabella delle misure con il traferro consigliato già calcolato."),
    'setting-the-air-gap/4/point2': ('705f03b8',
        "!Serve **Chrome o Edge**: la pagina parla con la scheda via Web Serial, che Safari e Firefox non hanno. E va servita da localhost, non aperta come file."),
    'setting-the-air-gap/4/point3': ('656b8fd4',
        "!Prima chiudi ogni altro monitor seriale: quello dell'IDE, o quello che `flash.sh` lascia aperto. La porta la può tenere un solo programma alla volta."),
    'setting-the-air-gap/5/title': ('455b8671',
        "Un piedino alla volta, e fai fare al disco un giro intero"),
    'setting-the-air-gap/5/point1': ('e3c0a697',
        "Ruota sul tavolo, lato telescopio in alto. Il piedino sulla faccia con l'anello attorno al magnete - si centra da solo e resta lì col suo peso - poi la schedina del sensore **avvitata sopra**."),
    'setting-the-air-gap/5/point2': ('93e3f459',
        "!Avvitata, non solo appoggiata. Una schedina appoggiata si solleva, e allora non è più il piedino a stabilire il traferro. È il primo errore da non fare due volte."),
    'setting-the-air-gap/5/point3': ('2510e5bd',
        "Per ogni piedino: `r` sulla pagina o sul monitor, **un giro intero** del disco a mano - prendilo dal bordo zigrinato - poi `s` per il riepilogo. Il giro intero conta perché il magnete non è mai centrato alla perfezione, e un punto solo lo premia o lo penalizza."),
    'setting-the-air-gap/5/point4': ('b9c83ad9',
        "Giudica sulla **magnitudine**, non sull'AGC. Con questo magnete a 3,3 V l'AGC resta a fondo scala a qualunque altezza, quindi non ti dice niente; la magnitudine è il numero che si muove."),
    'setting-the-air-gap/5/point5': ('ef66150d',
        "!Se nemmeno il piedino più basso riesce a far salire le letture, il magnete da {magnete_rif} mm così com'è è troppo debole e te ne serve uno più spesso. È una conclusione, non un fallimento."),
}
