# SPDX-FileCopyrightText: 2026 Matteo Beretta
# SPDX-License-Identifier: CERN-OHL-P-2.0
"""Italian catalogue for the chapter 'spring-and-connector'."""

CATALOGUE = {
    'spring-and-connector/title': ('f14b935f',
        'La molla e il connettore, prima del braccio'),
    'spring-and-connector/intro': ('e3771213',
        "Due cose entrano nella scatola prima del braccio. La molla di precarico e il suo scodellino stanno fra la loro sede nella scatola e il fianco della piastra del braccio: una volta montato il braccio, non c'è più spazio per metterli. E il connettore GX12 e il LED di stato vanno nella testata della scatola adesso, finché niente intralcia il dado."),
    'spring-and-connector/tool1': ('7f0921bd',
        'una chiave da 14 mm, per il dado del connettore GX12'),
    'spring-and-connector/tool2': ('ada9a302',
        'un saldatore, per cablare prima il connettore e il LED'),
    'spring-and-connector/1/title': ('2e537e39',
        'Il connettore GX12, da fuori della testata'),
    'spring-and-connector/1/point1': ('56ead93a',
        'Cablali prima, sul banco: due fili sui pin del GX12, per il morsetto dei 12 V sulla scheda (J3), e due sui piedini del LED, per la sua spina JST XH a 2 vie (J5). Lasciali abbastanza lunghi da arrivare alla scheda: la scheda sta sul pannellino, e il pannellino si toglie verso il basso. Una volta nella testata, il saldatore non ci entra più.'),
    'spring-and-connector/1/point2': ('58718981',
        'La testata della scatola è la parete piana in fondo. Il connettore GX12 entra nel suo foro da Ø{gx12_foro} mm **da fuori**, coi pin davanti, finché il corpo non appoggia sulla faccia esterna.'),
    'spring-and-connector/1/point3': ('bde8262d',
        'Tienilo lì: il dado si monta da dentro nel passo successivo.'),
    'spring-and-connector/2/title': ('8913ebf5',
        'Il suo dado e il LED di stato, da dentro'),
    'spring-and-connector/2/point1': ('41009ca2',
        "Entra con la mano dall'apertura dell'elettronica nel fondo. Avvita il dado sul connettore da dentro e serralo contro la faccia interna della testata."),
    'spring-and-connector/2/point2': ('187d73b3',
        'Il LED di stato sta appena sopra il connettore: spingilo nel suo foro da dentro finché il collarino non si ferma sulla parete.'),
    'spring-and-connector/2/point3': ('2b01b097',
        'Lascia dentro i fili di tutti e due abbastanza lunghi da arrivare alla scheda: la scheda sta sul pannellino, e il pannellino si toglie verso il basso, quindi quei fili devono poterlo seguire.'),
    'spring-and-connector/3/title': ('cfc1b905',
        'La molla e lo scodellino, nella loro sede nella scatola'),
    'spring-and-connector/3/point1': ('fd4f88dd',
        "Trova il mozzetto dentro la scatola, sulla parete esterna, in linea col braccio. La molla ci entra **da dentro**, spinta verso l'esterno finché non va a fondo. (La molla del prototipo viene da una molletta per i panni: filo da {molla_filo} mm, Ø{molla_esterno} mm esterno. Va bene qualunque molla con queste misure e circa {molla_k} N/mm.)"),
    'spring-and-connector/3/point2': ('14d5e1c3',
        "Lo scodellino va sull'estremità esterna della molla, col lato concavo verso la molla: è lì che spingerà la vite del precarico."),
    'spring-and-connector/3/point3': ('8b61268c',
        'La scatola è capovolta e la botola sotto il motore è ancora aperta: si entra da lì. Porta su molla e scodellino attraverso la botola, avvicinali alla sede e spingili dentro lungo il suo asse.'),
    'spring-and-connector/3/point4': ('894b9d5a',
        'La molla è lunga {molla_libera} mm libera e finirà lunga {molla_montata} mm a macchina montata. Adesso non regolare niente: a questo serve il grano, una volta montato il braccio (capitolo {cap_setting_the_preload}).'),
}
