// SPDX-FileCopyrightText: 2026 Matteo Beretta
// SPDX-License-Identifier: MIT

// Wheelly - firmware of the filter wheel.
//
// It runs on a Seeed XIAO ESP32-S3. It talks to the Raspberry over USB, with a
// line-based text protocol: it can be read and written by hand from a serial
// monitor, and that is on purpose. The vocabulary lives in wheelly_protocol.h,
// the same file the INDI driver compiles on the other side of the cable.
//
// This file does almost nothing: it switches things on and goes round in
// circles. Everything that decides lives in wheel.cpp and dialog.cpp, which
// contain not a line of Arduino and are also compiled for the PC, where they
// pass the tests. Down here there is only the link between the two halves.
//
// To upload it:  cd firmware && ./flash.sh wheelly
// To try it by hand, without a wheel: firmware/test/firmware_bench.cpp compiles
// this same logic for the Mac.
//
// THE WIRING, as the board is actually soldered. It is not a proposal any more:
// it comes from mechanics/wheelly-cad/src/wiring.py, the drawing the board
// was built from, and firmware/test/test_pins.py fails if the two drift.
//
//     AS5600       SDA -> D4, SCL -> D5, powered at 3.3 V
//     TMC2208      STEP -> D0, DIR -> D1, EN -> D3
//                  single-wire UART: D8 (TX, through 1 kohm) and D9 (RX)
//     LED          D10, external, off except on a fault
//
// EN carries the 10 k pull-up to VIO: the driver stays off at every moment the
// XIAO is not driving that pin, reset and boot included.

#include "dialog.h"
#include "mechanics_esp32.h"
#include "storage_esp32.h"
#include "wheel.h"

using namespace wheelly;

static const char FW_VERSION[] = "0.1.0";

// The output: the lines go onto USB. It is the only piece of transport in the
// firmware, and it is three lines, because the dialog does not know what a
// serial port is.
class UsbOutput : public Output
{
    public:
        void line(const char *text) override
        {
            Serial.print(text);
            Serial.print('\n');
        }
};

static Pins pins;
static MechanicsEsp32 mechanics(pins);
static StorageEsp32 storage;
static Wheel wheel(mechanics, storage);
static UsbOutput output;
// The serial number is not made up: it is the chip's MAC, which is unique and
// burnt in at the factory. It tells two wheels on the same computer apart.
// The buffer is filled in setup(), but its address can be given to the dialog
// right now: the dialog keeps the pointer, not a copy.
static char serial_number[13] = "?";

static Dialog dialog(wheel, output, FW_VERSION, serial_number);

static void make_serial_number()
{
    const uint64_t mac = ESP.getEfuseMac();
    snprintf(serial_number, sizeof(serial_number), "%04lX%08lX",
             (unsigned long)(mac >> 32) & 0xFFFFUL,
             (unsigned long)(mac & 0xFFFFFFFFUL));
}

void setup()
{
    Serial.begin(115200);
    // No waiting for the monitor to open: the wheel has to work even when
    // attached to a Raspberry nobody is looking at.

    make_serial_number();

    storage.begin();
    mechanics.begin();
    wheel.begin();
    // the LED mode is a saved choice: "steady on" has to be on from power-up
    mechanics.led(wheel.led_mode() == LedMode::ON);
}

void loop()
{
    // Three things, and none that blocks. The loop must never stop and wait:
    // 'status' has to be answered even while the wheel is moving, and the LED's
    // Morse is generated by looking at the clock instead of with delays.
    wheel.step();
    dialog.step();

    while (Serial.available() > 0) {
        dialog.receive((char)Serial.read());
    }
}
